// Else Home — Product Data

const products = [

  // ═══════════════════════════════════════════════════════
  // BED BASE SETS  (19)
  // ═══════════════════════════════════════════════════════

  {
    id: 'bb-01', name: 'Atlas Platform Base',
    category: 'bed-base', subcategory: 'Platform',
    shortDesc: 'Clean-lined platform base with precision upholstery.',
    description: 'The Atlas defines the minimalist platform aesthetic — engineered with a solid timber subframe, full-perimeter upholstery, and a hidden leg system that creates a seamless floor-level profile. Available in 40+ fabric options and all standard sizes.',
    features: ['Solid hardwood subframe', 'Full-perimeter precision upholstery', 'Hidden leg system', 'Custom dimensions on request', 'Contract-grade materials throughout'],
    specs: { 'Construction': 'Solid hardwood + MDF composite', 'Upholstery': 'Full fabric coverage', 'Standard Leg Height': '28 cm', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height adjustment', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'oyster', 'slate', 'onyx', 'mist'],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Atlas+Platform+Base',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Atlas+Platform',
    featured: true,
  },
  {
    id: 'bb-02', name: 'Meridian Low Base',
    category: 'bed-base', subcategory: 'Platform',
    shortDesc: 'Low-profile platform base with architectural presence.',
    description: 'The Meridian sits just 14 cm from floor level, engineered for contemporary interiors that demand a grounded, minimal aesthetic. A solid hardwood frame wrapped in precision upholstery — no exposed fixings, no compromise.',
    features: ['14 cm floor clearance', 'Solid hardwood structural frame', 'Integrated base panel system', 'Flush edge finishing', 'Matching headboard range'],
    specs: { 'Construction': 'Engineered hardwood', 'Floor Clearance': '14 cm', 'Upholstery': 'Full perimeter', 'Weight Capacity': '280 kg', 'Sizes Available': 'Double to Super King + Custom' },
    customOptions: ['Fabric selection', 'Floor clearance adjustment', 'Headboard integration'],
    fabrics: ['sand', 'sage', 'storm', 'charcoal', 'oyster', 'cream'],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Meridian+Low+Base',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Meridian+Low',
    featured: false,
  },
  {
    id: 'bb-03', name: 'Vault Hydraulic Base',
    category: 'bed-base', subcategory: 'Storage',
    shortDesc: 'Full-access hydraulic ottoman with gas-lift mechanism.',
    description: 'The Vault offers maximum under-bed storage via a full-access gas-lift mechanism rated for 15+ years of daily operation. Waterproof base lining, reinforced hinge system, and contract-grade upholstery as standard.',
    features: ['Full-opening hydraulic lid', 'Gas-lift rated 200 kg', 'Waterproof non-woven base lining', 'Reinforced hinge mechanism', 'Contract-grade durability standard'],
    specs: { 'Mechanism': 'Gas-lift hydraulic', 'Storage Access': 'Full-width opening', 'Lid Load Rating': '200 kg', 'Lining': 'Waterproof non-woven', 'Sizes Available': 'Double to Super King + Custom' },
    customOptions: ['Fabric selection', 'Lift direction (end or side)', 'Custom interior lining', 'Headboard pairing'],
    fabrics: ['ivory', 'anthracite', 'camel', 'forest', 'stone', 'charcoal'],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Vault+Hydraulic+Base',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Vault+Storage',
    featured: true,
  },
  {
    id: 'bb-04', name: 'Repository Drawer Base',
    category: 'bed-base', subcategory: 'Storage',
    shortDesc: 'Two-drawer base with soft-close dovetail construction.',
    description: 'Two full-extension drawers with soft-close undermount rails and dovetail-joined carcasses. Felt-lined interiors and an anti-tip safety system. Engineered for hotel contracts and high-use environments.',
    features: ['2× full-extension drawers', 'Soft-close undermount rails', 'Dovetail drawer construction', 'Felt-lined interiors', 'Anti-tip safety mechanism'],
    specs: { 'Drawers': '2× full-extension', 'Rail Type': 'Undermount soft-close', 'Interior': 'Felt-lined', 'Drawer Depth': '35 cm standard', 'Sizes Available': 'King to Super King + Custom' },
    customOptions: ['Fabric selection', 'Drawer position (side or end)', 'Interior lining material', 'Custom dimensions'],
    fabrics: ['linen', 'navy-fabric', 'stone', 'ebony', 'cream'],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Repository+Drawer+Base',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Repository',
    featured: false,
  },
  {
    id: 'bb-05', name: 'Contour Upholstered Set',
    category: 'bed-base', subcategory: 'Upholstered',
    shortDesc: 'Matched base and headboard set with piped edge detail.',
    description: 'A fully matched upholstered base and headboard set with consistent finishing throughout — piped or plain edge detailing, deep HR foam headboard core, and optional button finish. Engineered for hotel and contract environments.',
    features: ['Matched base and headboard', 'HR foam headboard core (10 cm)', 'Piped or plain edge detailing', 'Optional button finish', 'Custom fabric throughout'],
    specs: { 'Set Includes': 'Base + headboard', 'Headboard Depth': '10 cm', 'Fill': 'HR foam + fibre layer', 'Edge Detail': 'Piped or plain', 'Sizes Available': 'Double to Super King + Custom' },
    customOptions: ['Fabric selection', 'Detailing (piped / plain / button)', 'Headboard height', 'Custom dimensions'],
    fabrics: ['ecru', 'cognac', 'pewter', 'midnight', 'ivory', 'oyster'],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Contour+Upholstered+Set',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Contour+Set',
    featured: true,
  },
  {
    id: 'bb-06', name: 'Chancellor Channel Set',
    category: 'bed-base', subcategory: 'Upholstered',
    shortDesc: 'Vertical channel-tufted headboard with divan base.',
    description: 'Clean vertical channel stitching on a deep-padded headboard, paired with a matching divan base. A refined hotel aesthetic achieved through geometric precision. Wall-fix strut option available.',
    features: ['Vertical channel stitching', '12 cm deep padding', 'Reinforced headboard frame', 'Optional wall-fix strut', 'Matched base fabric'],
    specs: { 'Headboard': 'Vertical channel tufted', 'Padding': '12 cm', 'Wall Fix': 'Optional strut', 'Stitching': 'Machine channel', 'Sizes Available': 'Single to Super King' },
    customOptions: ['Fabric selection', 'Channel width', 'Headboard height', 'Wall-fix strut'],
    fabrics: ['cream', 'mist', 'slate', 'onyx', 'charcoal', 'stone'],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Chancellor+Channel+Set',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Chancellor',
    featured: false,
  },
  {
    id: 'bb-07', name: 'Crest Button-Tufted Set',
    category: 'bed-base', subcategory: 'Upholstered',
    shortDesc: 'Hand button-tufted headboard with continental base.',
    description: 'Hand button-tufted headboard with diamond or square pattern, meticulous button placement, and a deep HR foam core. Paired with a continental divan base — a timeless construction for residential and boutique hotel use.',
    features: ['Hand button-tufted finish', 'Diamond or square tufting pattern', 'HR foam + fibre core', 'Self-covered fabric buttons', 'Continental divan base'],
    specs: { 'Tufting': 'Hand-placed buttons', 'Pattern': 'Diamond or square', 'Core': 'HR35 foam + fibre', 'Buttons': 'Self-covered fabric', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Fabric selection', 'Tufting pattern', 'Button spacing', 'Headboard height'],
    fabrics: ['oyster', 'biscuit', 'taupe', 'graphite', 'sand', 'ecru'],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Crest+Button-Tufted+Set',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Crest+Button',
    featured: false,
  },
  {
    id: 'bb-08', name: 'Pinnacle Wingback Set',
    category: 'bed-base', subcategory: 'Wingback',
    shortDesc: 'Statement wingback headboard with divan base.',
    description: 'Full architectural wingback headboard with deeply padded wrap-around wings, available in heights up to 180 cm. A statement piece for luxury hotel suites and premium residential contracts.',
    features: ['Full architectural wing structure', 'Oversized proportions', 'Metal leg finish options', '20 cm deep padded wings', 'Height up to 180 cm available'],
    specs: { 'Headboard': 'Full wingback', 'Wing Depth': '20 cm', 'Legs': 'Chrome / brushed brass / matt black', 'Max Height': '180 cm', 'Sizes Available': 'King to Super King + Custom' },
    customOptions: ['Fabric selection', 'Wing dimensions', 'Leg finish', 'Custom height'],
    fabrics: ['sand', 'ocean', 'clay', 'carbon', 'cream', 'ivory'],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Pinnacle+Wingback+Set',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Pinnacle',
    featured: true,
  },
  {
    id: 'bb-09', name: 'Divide Continental Set',
    category: 'bed-base', subcategory: 'Continental',
    shortDesc: 'Split continental base with independent hydraulic halves.',
    description: 'A split two-piece continental base with independent hydraulic lift per section. Engineered for accessibility, ease of installation in confined spaces, and seamless mattress support across both halves.',
    features: ['Split two-piece construction', 'Independent hydraulic per half', 'Invisible joint connector', 'Euro-specification legs', 'Matching headboard available'],
    specs: { 'Sections': '2× independent halves', 'Storage': 'Independent hydraulic lift', 'Joint': 'Hidden connector system', 'Legs': 'Euro chrome standard', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Fabric selection', 'Leg finish', 'Headboard style', 'Storage direction'],
    fabrics: ['ivory', 'stone', 'slate', 'charcoal', 'onyx'],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Divide+Continental+Set',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Divide',
    featured: false,
  },
  {
    id: 'bb-10', name: 'Horizon Continental Set',
    category: 'bed-base', subcategory: 'Continental',
    shortDesc: 'Continental base with integral 800-count pocket spring layer.',
    description: 'A full-width continental base incorporating an 800-count pocket spring layer within the base itself, creating a secondary sleep surface beneath the mattress. Hardwood perimeter frame, euro legs, and matched headboard available.',
    features: ['800-count integral pocket spring layer', 'Tempered steel spring wire', 'Hardwood perimeter frame', 'Euro-specification leg system', 'Matching headboard range'],
    specs: { 'Spring Count': '800 per 150 cm', 'Spring Gauge': '1.2 mm tempered steel', 'Frame': 'Hardwood perimeter', 'Base Depth': '18 cm', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Fabric selection', 'Leg finish', 'Headboard design', 'Spring tension'],
    fabrics: ['alabaster', 'linen', 'sand', 'onyx', 'stone'],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Horizon+Continental+Set',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Horizon',
    featured: false,
  },
  {
    id: 'bb-11', name: 'Archive Ottoman Standard',
    category: 'bed-base', subcategory: 'Ottoman',
    shortDesc: 'End-opening ottoman base for contract environments.',
    description: 'End-lift ottoman base engineered for high-use contract environments. Heavy-duty gas pistons, slate-lined storage bay, and contract-grade fabric upholstery. Anti-sag perimeter support as standard.',
    features: ['End-lift opening design', 'Heavy-duty gas pistons', 'Slate-lined storage base', 'Contract-grade upholstery', 'Anti-sag perimeter support'],
    specs: { 'Opening': 'End-lift', 'Storage Depth': '28 cm', 'Mechanism': 'Heavy-duty gas pistons', 'Lining': 'Grey non-woven slate', 'Sizes Available': 'Single to Super King' },
    customOptions: ['Fabric selection', 'Opening direction', 'Interior lining', 'Custom dimensions'],
    fabrics: ['charcoal', 'slate', 'stone', 'onyx', 'graphite'],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Archive+Ottoman+Standard',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Archive',
    featured: false,
  },
  {
    id: 'bb-12', name: 'Archive Ottoman Premium',
    category: 'bed-base', subcategory: 'Ottoman',
    shortDesc: 'Full-opening ottoman with maximum storage access.',
    description: 'Full-access ottoman with a lateral side-rise mechanism providing unrestricted access to the entire storage volume. Hardwood structural frame, premium fabric lining, and silent gas-lift system.',
    features: ['Full-access lateral opening', 'Silent side-rise mechanism', 'Solid hardwood frame', 'Premium fabric interior lining', 'Silent lift system'],
    specs: { 'Opening': 'Side-rise / full access', 'Storage Depth': '32 cm', 'Frame': 'Solid hardwood', 'Lining': 'Premium fabric', 'Sizes Available': 'King to Super King' },
    customOptions: ['Fabric selection', 'Interior lining fabric', 'Mechanism type', 'Custom dimensions'],
    fabrics: ['ivory', 'cream', 'oyster', 'ecru', 'alabaster'],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Archive+Ottoman+Premium',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Archive+Premium',
    featured: false,
  },
  {
    id: 'bb-13', name: 'Elevate TV Lift Base',
    category: 'bed-base', subcategory: 'TV Lift',
    shortDesc: 'Motorized TV lift base with silent linear actuator.',
    description: 'Motorized television lift integrated into the end panel of the bed base. A silent linear actuator supports screens from 40–65" with hidden cable management and RF remote control as standard.',
    features: ['Silent linear actuator', '40–65" screen capacity', 'RF remote handset', 'Integrated cable routing', 'Anti-vibration TV mount'],
    specs: { 'Motor': 'Silent linear actuator', 'Screen Size': '40–65"', 'Control': 'RF remote + app option', 'Rise Time': '6–8 seconds', 'Sizes Available': 'King to Super King' },
    customOptions: ['Fabric selection', 'Screen bracket size', 'Control system', 'Cabinet position'],
    fabrics: ['charcoal', 'onyx', 'graphite', 'midnight', 'carbon'],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Elevate+TV+Lift+Base',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Elevate',
    featured: false,
  },
  {
    id: 'bb-14', name: 'Axis Adjustable Entry',
    category: 'bed-base', subcategory: 'Adjustable',
    shortDesc: 'Adjustable base with head and foot articulation.',
    description: 'Entry-level adjustable base with independent head (0–70°) and foot (0–40°) articulation. Whisper-quiet DC motor, anti-snore preset, and zero-gravity position included as standard.',
    features: ['Head articulation 0–70°', 'Foot articulation 0–40°', 'Whisper-quiet DC motor', 'Anti-snore preset position', 'Zero-gravity preset', 'Wireless remote'],
    specs: { 'Articulation': 'Head + foot independent', 'Head Range': '0–70°', 'Foot Range': '0–40°', 'Motor': 'DC whisper-quiet', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Fabric selection', 'Remote type', 'Under-bed lighting', 'USB charging ports'],
    fabrics: ['slate', 'charcoal', 'stone', 'graphite'],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Axis+Adjustable+Entry',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Axis+Entry',
    featured: false,
  },
  {
    id: 'bb-15', name: 'Axis Adjustable Pro',
    category: 'bed-base', subcategory: 'Adjustable',
    shortDesc: 'Full-featured adjustable base with massage and LED.',
    description: 'The complete adjustable base — full articulation, dual-zone wave massage, tunable under-bed LED lighting, Bluetooth app control, and USB-A/C charging ports. Split-king configuration available.',
    features: ['Full articulation + lumbar lift', 'Dual-zone wave massage', 'Tunable under-bed LED', 'Bluetooth app + voice control', 'USB-A and USB-C ports'],
    specs: { 'Articulation': 'Head + foot + lumbar', 'Massage': 'Dual-zone wave', 'Lighting': 'Tunable LED strip', 'Connectivity': 'Bluetooth + Alexa', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Split-king configuration', 'Massage presets', 'LED colour temperature', 'OEM app branding'],
    fabrics: ['onyx', 'graphite', 'midnight', 'charcoal'],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Axis+Adjustable+Pro',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Axis+Pro',
    featured: false,
  },
  {
    id: 'bb-16', name: 'Linden Divan Classic',
    category: 'bed-base', subcategory: 'Divan',
    shortDesc: 'Classic fabric divan with castored or fixed legs.',
    description: 'Traditional divan base with fabric-covered top deck, platform edge, and a choice of castored or fixed wooden legs. Optional 2 or 4-drawer configuration. Available in all standard sizes.',
    features: ['Fabric-covered top deck', 'Platform or valance edge', 'Castors or fixed wood legs', 'Optional 2/4 drawer', 'Matching headboard range'],
    specs: { 'Top Deck': 'Fabric covered', 'Edge': 'Platform or valance', 'Legs': 'Castors or fixed wood', 'Drawers': 'Optional 2 or 4', 'Sizes Available': 'Single to Super King' },
    customOptions: ['Fabric selection', 'Leg style', 'Drawer configuration', 'Headboard pairing'],
    fabrics: ['linen', 'cream', 'sand', 'stone', 'charcoal', 'oyster'],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Linden+Divan+Classic',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Linden+Classic',
    featured: false,
  },
  {
    id: 'bb-17', name: 'Linden Divan Modern',
    category: 'bed-base', subcategory: 'Divan',
    shortDesc: 'Contemporary divan with metal leg detail.',
    description: 'A contemporary take on the divan — metal leg finish options, low-profile design, and a solid platform top. Clean architectural lines engineered for modern residential and boutique hotel contracts.',
    features: ['Metal leg finish options', 'Low-profile 22 cm clearance', 'Solid platform top', 'Contract-grade frame', 'Flush edge finishing'],
    specs: { 'Legs': 'Chrome / brushed brass / matt black', 'Height': '22 cm clearance', 'Top': 'Solid platform', 'Frame': 'MDF + hardwood composite', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Fabric selection', 'Leg metal finish', 'Custom height', 'Storage addition'],
    fabrics: ['onyx', 'slate', 'graphite', 'midnight', 'stone', 'charcoal'],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Linden+Divan+Modern',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Linden+Modern',
    featured: false,
  },
  {
    id: 'bb-18', name: 'Stratum Panel Base',
    category: 'bed-base', subcategory: 'Panel',
    shortDesc: 'Monolithic panel base with integrated side panels.',
    description: 'A full solid-panel base with integrated side panels creating a monolithic, architectural presence. Available in fabric upholstery or lacquer finish, with custom height options and floating headboard compatibility.',
    features: ['Integrated full-height side panels', 'No exposed frame or fixings', 'Fabric or lacquer finish', 'Custom height options', 'Floating headboard compatible'],
    specs: { 'Panels': 'Full-height integrated', 'Finish': 'Fabric or lacquer', 'Standard Height': '32 cm', 'Frame': 'MDF + timber core', 'Sizes Available': 'Double to Super King' },
    customOptions: ['Fabric or lacquer selection', 'Panel height', 'Floating headboard', 'Internal storage option'],
    fabrics: ['onyx', 'graphite', 'charcoal', 'midnight', 'carbon'],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Stratum+Panel+Base',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Stratum',
    featured: false,
  },
  {
    id: 'bb-19', name: 'Lattice Slatted Base',
    category: 'bed-base', subcategory: 'Slatted',
    shortDesc: 'Sprung slatted base with optimal mattress ventilation.',
    description: 'Flexible slatted base with sprung central slat zones and solid perimeter slats. Birch timber throughout, 60 mm gap standard, with a central support rail and adjustable leg height. Engineered for maximum mattress breathability and longevity.',
    features: ['Flexible sprung central zones', 'Solid perimeter slats', '60 mm slat gap standard', 'Birch laminate slats', 'Adjustable centre support rail'],
    specs: { 'Slat Material': 'Birch laminate', 'Gap': '60 mm standard', 'Spring Zones': '3 central zones', 'Centre Support': 'Adjustable rail', 'Sizes Available': 'Single to Super King' },
    customOptions: ['Slat gap specification', 'Frame height', 'Centre rail height', 'Headboard mounting'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Lattice+Slatted+Base',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Lattice',
    featured: false,
  },

  // ═══════════════════════════════════════════════════════
  // MATTRESSES  (6)
  // ═══════════════════════════════════════════════════════

  {
    id: 'mt-01', name: 'Foundation Pocket Spring',
    category: 'mattress', subcategory: 'Pocket Spring',
    shortDesc: '1000-count hand-nested springs with natural fillings.',
    description: '1000-count hand-nested pocket spring system with Belgian damask cover and traditional natural filling layers. A classic construction built with modern precision and available in custom spring counts.',
    features: ['1000 hand-nested pocket springs', 'Belgian damask ticking', 'Natural wool and cotton fillings', 'Hand-tufted finish', 'Dual-sided turnover design'],
    specs: { 'Spring Count': '1000 per 150 cm', 'Spring Type': 'Barrel pocket, hand-nested', 'Cover': 'Belgian damask', 'Fillings': 'Wool, cotton, coir', 'Depth': '24 cm' },
    customOptions: ['Spring count (800–2000)', 'Filling specification', 'Cover fabric selection', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Foundation+Pocket+Spring',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Foundation',
    featured: true,
    layers: [
      { label: 'Belgian Damask Ticking', color: '#f0edec' },
      { label: 'Natural Wool Layer', color: '#e8dcc8' },
      { label: 'Cotton Comfort Layer', color: '#f0e8d8' },
      { label: '1000 Pocket Spring System', color: '#d4cfc9' },
      { label: 'Coir Fibre Foundation', color: '#b8ae9a' },
      { label: 'Non-Woven Base', color: '#a09890' },
    ],
  },
  {
    id: 'mt-02', name: 'Dual Zone Pocket Spring',
    category: 'mattress', subcategory: 'Pocket Spring',
    shortDesc: 'Five-zone spring mapping for ergonomic spinal support.',
    description: 'A 5-zone pocket spring system with firmer lumbar support in the centre zones and softer shoulder support in the outer zones. Independent springs eliminate motion transfer between sleep partners.',
    features: ['5-zone spring mapping', 'Firmer lumbar zone (centre)', 'Softer shoulder support (outer)', 'Motion isolation between zones', 'Breathable stretch-knit cover'],
    specs: { 'Zones': '5-zone mapped', 'Lumbar Gauge': '1.4 mm steel', 'Shoulder Gauge': '1.0 mm steel', 'Cover': 'Stretch-knit', 'Depth': '26 cm' },
    customOptions: ['Zone configuration', 'Spring count per zone', 'Cover material', 'Comfort layer specification'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Dual+Zone+Pocket+Spring',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Dual+Zone',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-03', name: 'Contour Memory Foam',
    category: 'mattress', subcategory: 'Memory Foam',
    shortDesc: 'Four-layer CertiPUR-US memory foam construction.',
    description: 'A four-layer visco-elastic memory foam construction with open-cell technology for breathability. CertiPUR-US certified materials, cooling stretch-knit cover, and non-slip base fabric throughout.',
    features: ['4-layer construction', 'Open-cell visco-elastic foam', 'CertiPUR-US certified', 'Cooling stretch-knit cover', 'Non-slip base'],
    specs: { 'Layers': 'Comfort + transition + support + cover', 'Top Layer': '3 cm visco-elastic (40 kg/m³)', 'Transition': '3 cm HR foam (35 kg/m³)', 'Support Base': '14 cm HR foam', 'Depth': '20 cm' },
    customOptions: ['Layer specification', 'Foam density selection', 'Cover material', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Contour+Memory+Foam',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Contour',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-04', name: 'Arctic Gel Memory Foam',
    category: 'mattress', subcategory: 'Memory Foam',
    shortDesc: 'Gel-infused foam with phase-change cooling cover.',
    description: 'Gel-bead infused memory foam with a phase-change material cover. Active heat dissipation and breathable quilting make this the ideal specification for warm-climate markets and temperature-sensitive hotel environments.',
    features: ['Gel-bead infused top layer', 'Phase-change material cover', 'Active heat dissipation', 'Breathable quilted panel', 'Up to 3°C surface temperature reduction'],
    specs: { 'Top Layer': '4 cm gel-infused (45 kg/m³)', 'Cover': 'PCM stretch-knit', 'Gel Type': 'Phase-change micro-encapsulated', 'Cooling': 'Up to −3°C surface', 'Depth': '22 cm' },
    customOptions: ['Gel layer depth', 'PCM cover specification', 'Foam density', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Arctic+Gel+Memory+Foam',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Arctic+Gel',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-05', name: 'Natura Latex',
    category: 'mattress', subcategory: 'Latex',
    shortDesc: '100% natural Talalay latex, OEKO-TEX certified.',
    description: '100% natural Talalay latex mattress with OEKO-TEX Standard 100 certification. Naturally hypoallergenic, sustainably sourced, open-cell pincore ventilation, and GOTS organic cotton cover.',
    features: ['100% Talalay natural latex', 'OEKO-TEX Standard 100 certified', 'Naturally hypoallergenic', 'Open-cell pincore ventilation', 'GOTS organic cotton cover'],
    specs: { 'Material': '100% Talalay natural latex', 'Density': '75 kg/m³', 'Core': 'Pincore ventilated', 'Cover': 'GOTS organic cotton', 'Depth': '20 cm' },
    customOptions: ['Latex density (soft / medium / firm)', 'Cover material', 'Layer configuration', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Natura+Latex',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Natura',
    featured: true,
    layers: [],
  },
  {
    id: 'mt-06', name: 'Hybrid Elite',
    category: 'mattress', subcategory: 'Hybrid',
    shortDesc: 'Micro-coil base with memory foam comfort layer.',
    description: 'A 1200-count micro-coil support base combined with a visco-elastic memory foam comfort layer. The responsiveness of springs, the pressure relief of foam — in a single precision-engineered construction.',
    features: ['1200 micro-coils per 150 cm', 'Visco-elastic comfort layer', 'Zoned support construction', 'Breathable foam perimeter border', 'Knitted pillow-top cover'],
    specs: { 'Coil Count': '1200 per 150 cm', 'Coil Height': '5 cm', 'Comfort Foam': '3 cm visco-elastic', 'Border': 'Breathable perimeter foam', 'Depth': '25 cm' },
    customOptions: ['Coil count specification', 'Foam layer depth', 'Comfort level', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Hybrid+Elite',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Hybrid',
    featured: false,
    layers: [],
  },

  // ═══════════════════════════════════════════════════════
  // TOPPERS  (3)
  // ═══════════════════════════════════════════════════════

  {
    id: 'tp-01', name: 'Cloud Memory Topper',
    category: 'topper', subcategory: 'Memory Foam',
    shortDesc: '5 cm visco-elastic topper with cooling cover.',
    description: '5 cm visco-elastic memory foam topper (45 kg/m³) for mattress surface enhancement. Cooling stretch-knit cover, anti-slip base, and 4-point corner strap system. Machine-washable cover.',
    features: ['5 cm visco-elastic foam (45 kg/m³)', 'Cooling stretch-knit cover', 'Anti-slip base fabric', '4-point corner strap system', 'Machine-washable removable cover'],
    specs: { 'Foam': 'Visco-elastic (45 kg/m³)', 'Depth': '5 cm', 'Cover': 'Cooling stretch-knit', 'Base': 'Non-slip fabric', 'Straps': '4× adjustable corners' },
    customOptions: ['Foam density', 'Depth (3 / 5 / 7 cm)', 'Cover material', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Cloud+Memory+Topper',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Cloud+Topper',
    featured: false,
  },
  {
    id: 'tp-02', name: 'Natura Latex Topper',
    category: 'topper', subcategory: 'Latex',
    shortDesc: 'Natural Dunlop latex topper with pincore ventilation.',
    description: 'Natural Dunlop latex topper (65 kg/m³) with pincore ventilation and OEKO-TEX certification. Adds pressure-relief responsiveness and natural breathability to any mattress. GOTS organic cotton cover.',
    features: ['Natural Dunlop process latex', 'Pincore ventilation pattern', 'OEKO-TEX certified', 'GOTS organic cotton cover', 'Elasticated anchor straps'],
    specs: { 'Material': 'Natural Dunlop latex', 'Density': '65 kg/m³', 'Depth': '4 cm', 'Cover': 'GOTS organic cotton', 'Ventilation': 'Pincore pattern' },
    customOptions: ['Latex density', 'Depth (3 / 4 / 6 cm)', 'Cover selection', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Natura+Latex+Topper',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Latex+Topper',
    featured: false,
  },
  {
    id: 'tp-03', name: 'Wool & Cotton Topper',
    category: 'topper', subcategory: 'Natural Fibre',
    shortDesc: 'Pure British wool topper with cotton cambric casing.',
    description: 'Pure British wool fill encased in cotton cambric — a natural temperature-regulating topper ideal for hotel and contract environments. 400 gsm standard fill weight. Machine washable at 40°C.',
    features: ['Pure British wool fill', '400 gsm fill weight standard', 'Cotton cambric 180TC outer', 'Temperature-regulating year-round', 'Machine washable at 40°C'],
    specs: { 'Fill': 'Pure British wool', 'Fill Weight': '400 gsm', 'Casing': 'Cotton cambric 180TC', 'Depth': '3 cm', 'Wash': 'Machine wash 40°C' },
    customOptions: ['Fill weight (300 / 400 / 500 gsm)', 'Casing thread count', 'Dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Wool+%26+Cotton+Topper',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Wool+Topper',
    featured: false,
  },
];

// ═══════════════════════════════════════════════════════
// FABRIC PALETTE
// ═══════════════════════════════════════════════════════

const fabrics = {
  alabaster:    { name: 'Alabaster',       hex: '#F2EDE4', group: 'neutral' },
  linen:        { name: 'Natural Linen',   hex: '#D8CAB0', group: 'neutral' },
  oyster:       { name: 'Oyster',          hex: '#E8DFD0', group: 'neutral' },
  cream:        { name: 'Warm Cream',      hex: '#F0E8D8', group: 'neutral' },
  ecru:         { name: 'Écru',            hex: '#EDE4D3', group: 'neutral' },
  biscuit:      { name: 'Biscuit',         hex: '#D4B896', group: 'neutral' },
  ivory:        { name: 'Ivory',           hex: '#FAFAF5', group: 'neutral' },
  sand:         { name: 'Desert Sand',     hex: '#C8A87A', group: 'warm'    },
  camel:        { name: 'Camel',           hex: '#B8934A', group: 'warm'    },
  cognac:       { name: 'Cognac',          hex: '#9B5E3A', group: 'warm'    },
  clay:         { name: 'Clay',            hex: '#A87060', group: 'warm'    },
  taupe:        { name: 'Taupe',           hex: '#9E907C', group: 'neutral' },
  stone:        { name: 'Stone',           hex: '#B8B0A8', group: 'cool'    },
  mist:         { name: 'Dove Mist',       hex: '#C8CDD4', group: 'cool'    },
  sage:         { name: 'Sage Green',      hex: '#8A9E8B', group: 'cool'    },
  slate:        { name: 'Slate Blue',      hex: '#7B8FA1', group: 'cool'    },
  ocean:        { name: 'Ocean',           hex: '#4A6E8A', group: 'cool'    },
  forest:       { name: 'Forest',          hex: '#4A6249', group: 'cool'    },
  storm:        { name: 'Storm Grey',      hex: '#6A7280', group: 'cool'    },
  pewter:       { name: 'Pewter',          hex: '#8A8E94', group: 'cool'    },
  graphite:     { name: 'Graphite',        hex: '#4A4E54', group: 'dark'    },
  charcoal:     { name: 'Charcoal',        hex: '#3A3D42', group: 'dark'    },
  midnight:     { name: 'Midnight Blue',   hex: '#1B2C4A', group: 'dark'    },
  'navy-fabric':{ name: 'Deep Navy',       hex: '#03163D', group: 'dark'    },
  onyx:         { name: 'Onyx',            hex: '#2C2C2C', group: 'dark'    },
  ebony:        { name: 'Ebony',           hex: '#1E1E1E', group: 'dark'    },
  anthracite:   { name: 'Anthracite',      hex: '#2D3032', group: 'dark'    },
  carbon:       { name: 'Carbon',          hex: '#383838', group: 'dark'    },
};

// ═══════════════════════════════════════════════════════
// CATEGORIES
// ═══════════════════════════════════════════════════════

const categories = [
  {
    id: 'bed-base',
    name: 'Bed Base Systems',
    count: 19,
    description: 'Platform, storage, ottoman, adjustable, wingback, and divan bases — engineered for export markets, hotel contracts, and premium residential use.',
    image: 'https://placehold.co/800x600/f0edec/03163D?text=Bed+Base+Systems',
  },
  {
    id: 'mattress',
    name: 'Mattresses',
    count: 6,
    description: 'Pocket spring, memory foam, latex, and hybrid mattresses built to custom specifications for every comfort requirement.',
    image: 'https://placehold.co/800x600/e5e2e1/03163D?text=Mattresses',
  },
  {
    id: 'topper',
    name: 'Toppers',
    count: 3,
    description: 'Memory foam, natural latex, and wool topper systems for mattress enhancement and hotel bedding programmes.',
    image: 'https://placehold.co/800x600/dcd9d9/03163D?text=Toppers',
  },
];

// ═══════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════

function getProductById(id) {
  return products.find(p => p.id === id) || null;
}

function getProductsByCategory(cat) {
  return products.filter(p => p.category === cat);
}

function getFeaturedProducts() {
  return products.filter(p => p.featured);
}

function getFabric(id) {
  return fabrics[id] || { name: id, hex: '#ccc', group: 'neutral' };
}

function getRelated(product, limit = 4) {
  return products
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}
