// Else Home — Product Data
//
// PRODUCT IMAGES: Add photos to images/products/
//   Bed bases: use imageFile field (e.g. '1_aura_xxl.jpg')
//   Mattresses / toppers: name as [id]-main.jpg (e.g. mt-01-main.jpg)
//   Missing images fall back to the brand_assets placeholder for that category.

const baseProducts = [

  // ═══════════════════════════════════════════════════════
  // BED BASE SETS  (19)
  // ═══════════════════════════════════════════════════════

  {
    id: 'bb-01', name: 'Aura XXL',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Oversized upholstered bed base with premium fabric finish.',
    shortDesc_tr: 'Büyük boy döşemeli yatak tabanı, premium kumaş kaplama.',
    description: 'The Aura XXL delivers a bold, oversized silhouette engineered for premium residential and hotel contracts. Full-perimeter upholstery, solid hardwood subframe, and available in 40+ fabric options across all sizes.',
    description_tr: 'Aura XXL, premium konut ve otel sözleşmeleri için mühendislik anlayışıyla tasarlanmış cesur, büyük boy bir siluet sunar. Tam çevre döşeme, sağlam sert ahşap alt çerçeve ve tüm boyutlarda 40+ kumaş seçeneği.',
    features: ['Solid hardwood subframe', 'Full-perimeter precision upholstery', 'Oversized XXL proportions', 'Custom dimensions on request', 'Contract-grade materials throughout'],
    features_tr: ['Sağlam sert ahşap alt çerçeve', 'Tam çevre hassas döşeme', 'Büyük boy XXL oranlar', 'Talep üzerine özel boyutlar', 'Her yerde sözleşme kaliteli malzeme'],
    specs: { 'Construction': 'Solid hardwood + MDF composite', 'Upholstery': 'Full fabric coverage', 'Standard Leg Height': '28 cm', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Yapı': 'Sağlam sert ahşap + MDF kompozit', 'Döşeme': 'Tam kumaş kaplama', 'Standart Ayak Yüksekliği': '28 cm', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height adjustment', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'oyster', 'slate', 'onyx', 'mist'],
    imageFile: '1_aura_xxl.jpg',
    featured: true,
  },
  {
    id: 'bb-02', name: 'Berlin',
    category: 'bed-base', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Architectural platform base with clean geometric lines.',
    shortDesc_tr: 'Temiz geometrik hatlarıyla mimari platform taban.',
    description: 'The Berlin is a refined platform base with strict geometric proportions and flush edge detailing. Solid hardwood frame, full upholstery, and a hidden leg system engineered for contemporary residential and contract environments.',
    description_tr: 'Berlin, sıkı geometrik oranlar ve düz kenar detaylarıyla rafine bir platform tabandır. Sağlam sert ahşap çerçeve, tam döşeme ve çağdaş konut ve sözleşme ortamları için mühendislik anlayışıyla tasarlanmış gizli ayak sistemi.',
    features: ['Solid hardwood structural frame', 'Flush edge finishing', 'Hidden leg system', 'Matching headboard range', 'Custom dimensions available'],
    features_tr: ['Sağlam sert ahşap yapısal çerçeve', 'Düz kenar kaplama', 'Gizli ayak sistemi', 'Uyumlu başlık aralığı', 'Özel boyutlar mevcut'],
    specs: { 'Construction': 'Engineered hardwood + MDF', 'Upholstery': 'Full perimeter', 'Weight Capacity': '280 kg', 'Leg Height': 'Adjustable', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Yapı': 'Mühendislik sert ahşap + MDF', 'Döşeme': 'Tam çevre', 'Ağırlık Kapasitesi': '280 kg', 'Ayak Yüksekliği': 'Ayarlanabilir', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg height adjustment', 'Headboard integration', 'Custom dimensions'],
    fabrics: ['sand', 'sage', 'storm', 'charcoal', 'oyster', 'cream'],
    imageFile: '2_berlin.jpg',
    featured: false,
  },
  {
    id: 'bb-03', name: 'Metropolis',
    category: 'bed-base', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Statement platform base designed for large-scale contracts.',
    shortDesc_tr: 'Büyük ölçekli sözleşmeler için tasarlanmış öne çıkan platform taban.',
    description: 'The Metropolis is engineered for statement residential and hospitality installations. Robust solid hardwood construction, deep upholstery profile, and a broad platform deck designed to anchor any room.',
    description_tr: 'Metropolis, öne çıkan konut ve konaklama tesisi kurulumları için mühendislik anlayışıyla tasarlanmıştır. Sağlam sert ahşap yapı, derin döşeme profili ve herhangi bir odayı çerçevelemek için tasarlanmış geniş platform güvertesi.',
    features: ['Broad platform deck profile', 'Solid hardwood frame', 'Full-perimeter upholstery', 'Contract-grade durability', 'Custom fabric and dimensions'],
    features_tr: ['Geniş platform güverte profili', 'Sağlam sert ahşap çerçeve', 'Tam çevre döşeme', 'Sözleşme kaliteli dayanıklılık', 'Özel kumaş ve boyutlar'],
    specs: { 'Construction': 'Solid hardwood + composite', 'Deck Width': 'Extended platform', 'Weight Capacity': '320 kg', 'Upholstery': 'Full coverage', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Yapı': 'Sağlam sert ahşap + kompozit', 'Güverte Genişliği': 'Geniş platform', 'Ağırlık Kapasitesi': '320 kg', 'Döşeme': 'Tam kaplama', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Deck height', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['ivory', 'anthracite', 'camel', 'forest', 'stone', 'charcoal'],
    imageFile: '3_metropolis.jpg',
    featured: true,
  },
  {
    id: 'bb-04', name: 'Perla XXL',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Luxury oversized base with refined upholstery detailing.',
    shortDesc_tr: 'Rafine döşeme detaylarıyla lüks büyük boy taban.',
    description: 'The Perla XXL combines oversized proportions with meticulous upholstery finishing. Piped or plain edge detail options, deep HR foam padding, and a solid hardwood frame — engineered for luxury hotel suites and premium residential projects.',
    description_tr: 'Perla XXL, büyük boy oranları titiz döşeme kaplamasıyla birleştirir. Boru veya düz kenar detay seçenekleri, derin HR köpük dolgu ve sağlam sert ahşap çerçeve — lüks otel süitleri ve premium konut projeleri için mühendislik anlayışıyla tasarlanmıştır.',
    features: ['Oversized XXL construction', 'Piped or plain edge detailing', 'Deep HR foam padding', 'Solid hardwood frame', 'Contract-grade fabric throughout'],
    features_tr: ['Büyük boy XXL yapı', 'Boru veya düz kenar detay', 'Derin HR köpük dolgu', 'Sağlam sert ahşap çerçeve', 'Her yerde sözleşme kaliteli kumaş'],
    specs: { 'Set Includes': 'Base + optional headboard', 'Padding': '8 cm HR foam', 'Edge Detail': 'Piped or plain', 'Weight Capacity': '300 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Set İçeriği': 'Taban + isteğe bağlı başlık', 'Dolgu': '8 cm HR köpük', 'Kenar Detayı': 'Borulu veya düz', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Edge detailing (piped / plain)', 'Headboard height', 'Custom dimensions'],
    fabrics: ['ecru', 'cognac', 'pewter', 'midnight', 'ivory', 'oyster'],
    imageFile: '4_perla_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-05', name: 'Business Class',
    category: 'bed-base', subcategory: 'Premium', subcategory_tr: 'Premium',
    shortDesc: 'Contract-grade premium base for hospitality environments.',
    shortDesc_tr: 'Konaklama ortamları için sözleşme kaliteli premium taban.',
    description: 'The Business Class is built exclusively for hotel and contract use — reinforced hardwood frame, contract-grade upholstery rated for 10+ year daily use, and precision manufacturing to exact specification.',
    description_tr: 'Business Class, özellikle otel ve sözleşme kullanımı için üretilmiştir — güçlendirilmiş sert ahşap çerçeve, 10+ yıl günlük kullanım için sertifikalı sözleşme kaliteli döşeme ve tam spesifikasyona göre hassas üretim.',
    features: ['Contract-grade hardwood frame', 'Heavy-duty upholstery construction', 'Anti-sag perimeter support', 'Hotel specification standard', 'Custom dimensions and fabrics'],
    features_tr: ['Sözleşme kaliteli sert ahşap çerçeve', 'Ağır hizmet döşeme yapısı', 'Sarkmayı önleyici çevre desteği', 'Otel spesifikasyon standardı', 'Özel boyutlar ve kumaşlar'],
    specs: { 'Construction': 'Reinforced hardwood', 'Upholstery Grade': 'Contract-rated', 'Weight Capacity': '350 kg', 'Durability': '10+ year rated', 'Sizes Available': 'Single to Super King' },
    specs_tr: { 'Yapı': 'Güçlendirilmiş sert ahşap', 'Döşeme Sınıfı': 'Sözleşme sertifikalı', 'Ağırlık Kapasitesi': '350 kg', 'Dayanıklılık': '10+ yıl sertifikalı', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Headboard style', 'Leg finish', 'Custom dimensions'],
    fabrics: ['cream', 'mist', 'slate', 'onyx', 'charcoal', 'stone'],
    imageFile: '5_business_class.jpg',
    featured: true,
  },
  {
    id: 'bb-06', name: 'Chester XXL',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Oversized Chester-style base with deep button tufting.',
    shortDesc_tr: 'Derin düğme kapitoneli büyük boy Chester tarzı taban.',
    description: 'The Chester XXL delivers the iconic deeply-tufted aesthetic at oversized scale. Hand-placed button tufting, 12 cm deep HR foam padding, and a solid hardwood frame make this a statement piece for luxury residential and boutique hotel contracts.',
    description_tr: 'Chester XXL, ikonik derin kapitoneli estetiği büyük ölçekte sunar. Elle yerleştirilen düğme kapitone, 12 cm derin HR köpük dolgu ve sağlam sert ahşap çerçeve, lüks konut ve butik otel sözleşmeleri için öne çıkan bir ürün yapar.',
    features: ['Hand button-tufted finish', 'Oversized XXL proportions', '12 cm deep HR foam padding', 'Diamond tufting pattern', 'Solid hardwood frame'],
    features_tr: ['Elle düğme kapitone kaplama', 'Büyük boy XXL oranlar', '12 cm derin HR köpük dolgu', 'Elmas kapitone deseni', 'Sağlam sert ahşap çerçeve'],
    specs: { 'Tufting': 'Hand-placed buttons', 'Padding': '12 cm HR foam + fibre', 'Buttons': 'Self-covered fabric', 'Frame': 'Solid hardwood', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Kapitone': 'Elle yerleştirilen düğmeler', 'Dolgu': '12 cm HR köpük + lif', 'Düğmeler': 'Kumaşla kaplı', 'Çerçeve': 'Sağlam sert ahşap', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Button spacing', 'Tufting pattern', 'Custom dimensions'],
    fabrics: ['oyster', 'biscuit', 'taupe', 'graphite', 'sand', 'ecru'],
    imageFile: '6_chester_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-07', name: 'Dormo XXL',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Wide-format upholstered base with wraparound profile.',
    shortDesc_tr: 'Çevreleyen profilli geniş formatlı döşemeli taban.',
    description: 'The Dormo XXL features a wraparound upholstered profile with an extended footboard design. Built for large residential and hospitality installations where scale and comfort define the space.',
    description_tr: 'Dormo XXL, uzatılmış ayak tahtası tasarımıyla çevreleyen döşemeli profile sahiptir. Ölçek ve konforun mekânı tanımladığı büyük konut ve konaklama tesisi kurulumları için üretilmiştir.',
    features: ['Wraparound upholstered profile', 'Extended footboard design', 'Oversized XXL format', 'Solid hardwood subframe', 'Full custom fabric options'],
    features_tr: ['Çevreleyen döşemeli profil', 'Uzatılmış ayak tahtası tasarımı', 'Büyük boy XXL format', 'Sağlam sert ahşap alt çerçeve', 'Tam özel kumaş seçenekleri'],
    specs: { 'Profile': 'Wraparound upholstered', 'Frame': 'Solid hardwood', 'Weight Capacity': '300 kg', 'Upholstery': 'Full perimeter + footboard', 'Sizes Available': 'King to Super King + Custom' },
    specs_tr: { 'Profil': 'Çevreleyen döşemeli', 'Çerçeve': 'Sağlam sert ahşap', 'Ağırlık Kapasitesi': '300 kg', 'Döşeme': 'Tam çevre + ayak tahtası', 'Mevcut Boyutlar': 'King\'den Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Footboard height', 'Leg finish', 'Custom dimensions'],
    fabrics: ['sand', 'ocean', 'clay', 'carbon', 'cream', 'ivory'],
    imageFile: '7_dormo_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-08', name: 'Elize XXL',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Sculptural oversized base with refined edge profile.',
    shortDesc_tr: 'Rafine kenar profilli heykelsi büyük boy taban.',
    description: 'The Elize XXL combines sculptural form with precision upholstery. A distinctive edge profile, deep-padded construction, and oversized format make it a signature product for luxury residential and premium hospitality.',
    description_tr: 'Elize XXL, heykelsi formu hassas döşemeyle birleştirir. Belirgin kenar profili, derin dolgulu yapı ve büyük boy format, onu lüks konut ve premium konaklama sektörü için imza ürün yapar.',
    features: ['Distinctive sculpted edge profile', 'Deep-padded construction', 'Oversized XXL proportions', 'Contract-grade materials', 'Custom fabric and dimensions'],
    features_tr: ['Belirgin heykelsi kenar profili', 'Derin dolgulu yapı', 'Büyük boy XXL oranlar', 'Sözleşme kaliteli malzeme', 'Özel kumaş ve boyutlar'],
    specs: { 'Profile': 'Sculpted edge', 'Padding': '10 cm HR foam', 'Frame': 'Solid hardwood composite', 'Weight Capacity': '300 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Profil': 'Heykelsi kenar', 'Dolgu': '10 cm HR köpük', 'Çerçeve': 'Sağlam sert ahşap kompozit', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Edge profile depth', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['ivory', 'stone', 'slate', 'charcoal', 'onyx'],
    imageFile: '8_elize_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-09', name: 'Genova',
    category: 'bed-base', subcategory: 'Continental', subcategory_tr: 'Kıta',
    shortDesc: 'Continental base with elegant tapered leg detail.',
    shortDesc_tr: 'Zarif konik ayak detaylı kıta tipi taban.',
    description: 'The Genova is a full continental base featuring an elegant tapered leg system and clean upholstered deck. Precision-engineered for residential and hospitality contracts where understated European design is required.',
    description_tr: 'Genova, zarif konik ayak sistemi ve temiz döşemeli güverte ile tam kıta tipi bir tabandır. Sade Avrupa tasarımının istendiği konut ve konaklama sözleşmeleri için hassas mühendislikle üretilmiştir.',
    features: ['Tapered leg detail', 'Full continental construction', 'Clean upholstered deck', 'Euro-specification frame', 'Matching headboard available'],
    features_tr: ['Konik ayak detayı', 'Tam kıta tipi yapı', 'Temiz döşemeli güverte', 'Avrupa spesifikasyon çerçevesi', 'Uyumlu başlık mevcut'],
    specs: { 'Type': 'Continental', 'Legs': 'Tapered euro-specification', 'Deck': 'Fully upholstered', 'Weight Capacity': '280 kg', 'Sizes Available': 'Double to Super King' },
    specs_tr: { 'Tür': 'Kıta tipi', 'Ayaklar': 'Konik Avrupa spesifikasyonu', 'Güverte': 'Tam döşemeli', 'Ağırlık Kapasitesi': '280 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Leg finish', 'Headboard style', 'Custom dimensions'],
    fabrics: ['ivory', 'cream', 'oyster', 'ecru', 'alabaster'],
    imageFile: '9_genova.jpg',
    featured: false,
  },
  {
    id: 'bb-10', name: 'Maladive',
    category: 'bed-base', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Low-slung platform base with resort-inspired proportions.',
    shortDesc_tr: 'Resort esinli oranlarla alçak profilli platform taban.',
    description: 'The Maladive is a low-slung platform base designed for contemporary resort and boutique hotel environments. Floor-level proportions, full upholstery, and clean-line construction create a relaxed yet refined aesthetic.',
    description_tr: 'Maladive, çağdaş resort ve butik otel ortamları için tasarlanmış alçak profilli platform tabandır. Zemin seviyesi oranlar, tam döşeme ve temiz hat yapısı gevşek ancak rafine bir estetik yaratır.',
    features: ['Low floor-level profile', 'Full-perimeter upholstery', 'Resort-spec construction', 'Custom dimensions available', 'Matching headboard range'],
    features_tr: ['Alçak zemin seviyesi profil', 'Tam çevre döşeme', 'Resort spesifikasyon yapısı', 'Özel boyutlar mevcut', 'Uyumlu başlık aralığı'],
    specs: { 'Floor Clearance': '14 cm', 'Upholstery': 'Full coverage', 'Frame': 'Engineered hardwood', 'Weight Capacity': '280 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Zemin Mesafesi': '14 cm', 'Döşeme': 'Tam kaplama', 'Çerçeve': 'Mühendislik sert ahşap', 'Ağırlık Kapasitesi': '280 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg height', 'Headboard integration', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'sand', 'onyx', 'stone'],
    imageFile: '10_maladive.jpg',
    featured: false,
  },
  {
    id: 'bb-11', name: 'Venus',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Curved upholstered base with soft-form silhouette.',
    shortDesc_tr: 'Yumuşak form siluetli eğri döşemeli taban.',
    description: 'The Venus introduces a soft-form curved silhouette to the Else Home range. Precision upholstery over a curved hardwood frame creates an organic, feminine aesthetic suited to premium residential and boutique hotel projects.',
    description_tr: 'Venus, Else Home aralığına yumuşak formlu eğri siluet kazandırır. Eğri sert ahşap çerçeve üzerine hassas döşeme, premium konut ve butik otel projelerine uygun organik, feminen bir estetik yaratır.',
    features: ['Curved hardwood frame', 'Soft-form upholstered silhouette', 'Full fabric coverage', 'Custom fabric selection', 'Matching headboard available'],
    features_tr: ['Eğri sert ahşap çerçeve', 'Yumuşak formlu döşemeli siluet', 'Tam kumaş kaplama', 'Özel kumaş seçimi', 'Uyumlu başlık mevcut'],
    specs: { 'Frame': 'Curved solid hardwood', 'Profile': 'Soft-form silhouette', 'Weight Capacity': '280 kg', 'Upholstery': 'Full curved coverage', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Çerçeve': 'Eğri sağlam sert ahşap', 'Profil': 'Yumuşak form siluet', 'Ağırlık Kapasitesi': '280 kg', 'Döşeme': 'Tam eğri kaplama', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Curve radius', 'Headboard style', 'Custom dimensions'],
    fabrics: ['charcoal', 'slate', 'stone', 'onyx', 'graphite'],
    imageFile: '11_venus.jpg',
    featured: false,
  },
  {
    id: 'bb-12', name: 'Lounge',
    category: 'bed-base', subcategory: 'Ottoman', subcategory_tr: 'Ottoman',
    shortDesc: 'Deep-lounging ottoman base with full-access storage.',
    shortDesc_tr: 'Tam erişimli depolama ile derin dinlenme ottoman tabanı.',
    description: 'The Lounge combines deep, reclined proportions with full-access ottoman storage. A gas-lift mechanism rated for daily contract use, waterproof interior lining, and available in 40+ fabric options.',
    description_tr: 'Lounge, derin dinlenme oranlarını tam erişimli ottoman depolamayla birleştirir. Günlük sözleşme kullanımı için sertifikalı gaz kaldırma mekanizması, su geçirmez iç astar ve 40+ kumaş seçeneği.',
    features: ['Full-access gas-lift storage', 'Deep lounge proportions', 'Waterproof interior lining', 'Heavy-duty gas pistons', 'Contract-grade construction'],
    features_tr: ['Tam genişlikte erişimli gaz kaldırma deposu', 'Derin dinlenme oranlar', 'Su geçirmez iç astar', 'Ağır hizmet gaz pistonları', 'Sözleşme kaliteli yapı'],
    specs: { 'Opening': 'Full-width access', 'Storage Depth': '30 cm', 'Mechanism': 'Gas-lift pistons', 'Lining': 'Waterproof non-woven', 'Sizes Available': 'King to Super King + Custom' },
    specs_tr: { 'Açılış': 'Tam genişlik erişimi', 'Depolama Derinliği': '30 cm', 'Mekanizma': 'Gaz kaldırma pistonları', 'Astar': 'Su geçirmez dokusuz kumaş', 'Mevcut Boyutlar': 'King\'den Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Opening direction', 'Interior lining', 'Custom dimensions'],
    fabrics: ['ivory', 'cream', 'oyster', 'ecru', 'alabaster'],
    imageFile: '12_lounge.jpg',
    featured: false,
  },
  {
    id: 'bb-13', name: 'Aura',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Classic Aura upholstered base — timeless proportions.',
    shortDesc_tr: 'Klasik Aura döşemeli taban — zamansız oranlar.',
    description: 'The original Aura — clean upholstered proportions with a solid hardwood frame and full fabric coverage. A versatile base for residential, hospitality, and export markets available in all standard sizes and 40+ fabrics.',
    description_tr: 'Orijinal Aura — sağlam sert ahşap çerçeve ve tam kumaş kaplamayla temiz döşemeli oranlar. Tüm standart boyutlarda ve 40+ kumaşta mevcut konut, konaklama ve ihracat pazarları için çok yönlü taban.',
    features: ['Solid hardwood subframe', 'Full-perimeter upholstery', 'Clean proportional design', 'Custom dimensions on request', 'Contract-grade materials'],
    features_tr: ['Sağlam sert ahşap alt çerçeve', 'Tam çevre döşeme', 'Temiz orantısal tasarım', 'Talep üzerine özel boyutlar', 'Sözleşme kaliteli malzeme'],
    specs: { 'Construction': 'Solid hardwood + MDF', 'Upholstery': 'Full fabric coverage', 'Leg Height': '28 cm standard', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Yapı': 'Sağlam sert ahşap + MDF', 'Döşeme': 'Tam kumaş kaplama', 'Ayak Yüksekliği': '28 cm standart', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height adjustment', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['linen', 'navy-fabric', 'stone', 'ebony', 'cream'],
    imageFile: '13_aura.jpg',
    featured: false,
  },
  {
    id: 'bb-14', name: 'California',
    category: 'bed-base', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Wide-deck platform base with California proportions.',
    shortDesc_tr: 'California oranlarıyla geniş güverteli platform taban.',
    description: 'The California takes its name from its generous width-to-height ratio — a wide, low platform deck that commands space. Solid hardwood construction, full upholstery, and custom sizing for all non-standard bed dimensions.',
    description_tr: 'California adını geniş yükseklik-genişlik oranından alır — alanı yöneten geniş, alçak platform güvertesi. Sağlam sert ahşap yapı, tam döşeme ve tüm standart dışı yatak boyutları için özel boyut.',
    features: ['Wide platform deck proportions', 'Low-profile design', 'Solid hardwood frame', 'Full-perimeter upholstery', 'Custom sizing available'],
    features_tr: ['Geniş platform güverte oranları', 'Alçak profil tasarımı', 'Sağlam sert ahşap çerçeve', 'Tam çevre döşeme', 'Özel boyutlandırma mevcut'],
    specs: { 'Profile': 'Wide low-platform', 'Construction': 'Solid hardwood', 'Weight Capacity': '300 kg', 'Upholstery': 'Full coverage', 'Sizes Available': 'California King + All Custom' },
    specs_tr: { 'Profil': 'Geniş alçak platform', 'Yapı': 'Sağlam sert ahşap', 'Ağırlık Kapasitesi': '300 kg', 'Döşeme': 'Tam kaplama', 'Mevcut Boyutlar': 'California King + Tüm Özel' },
    customOptions: ['Fabric selection', 'Deck height', 'Headboard integration', 'Custom dimensions'],
    fabrics: ['slate', 'charcoal', 'stone', 'graphite'],
    imageFile: '14_california.jpg',
    featured: false,
  },
  {
    id: 'bb-15', name: 'Chepau',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Distinctive upholstered base with signature profile.',
    shortDesc_tr: 'İmza profilli belirgin döşemeli taban.',
    description: 'The Chepau is a signature Else Home design — a distinctive upholstered profile with precise panel proportions and refined edge detail. Engineered for luxury residential projects and boutique hotel contracts.',
    description_tr: 'Chepau, bir Else Home imza tasarımı — hassas panel oranları ve rafine kenar detayıyla belirgin döşemeli profil. Lüks konut projeleri ve butik otel sözleşmeleri için mühendislik anlayışıyla tasarlanmıştır.',
    features: ['Signature panel proportions', 'Refined edge detailing', 'Solid hardwood frame', 'Full contract-grade upholstery', 'Custom fabric and dimensions'],
    features_tr: ['İmza panel oranları', 'Rafine kenar detayı', 'Sağlam sert ahşap çerçeve', 'Tam sözleşme kaliteli döşeme', 'Özel kumaş ve boyutlar'],
    specs: { 'Profile': 'Signature panel design', 'Frame': 'Solid hardwood', 'Weight Capacity': '300 kg', 'Upholstery': 'Full perimeter', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Profil': 'İmza panel tasarımı', 'Çerçeve': 'Sağlam sert ahşap', 'Ağırlık Kapasitesi': '300 kg', 'Döşeme': 'Tam çevre', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Panel detail', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['onyx', 'slate', 'graphite', 'midnight', 'stone', 'charcoal'],
    imageFile: '15_chepau.jpg',
    featured: false,
  },
  {
    id: 'bb-16', name: 'Chester',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Classic Chester button-tufted base and headboard set.',
    shortDesc_tr: 'Klasik Chester düğme kapitoneli taban ve başlık seti.',
    description: 'The Chester is the quintessential button-tufted design — hand-placed buttons, diamond tufting pattern, and deep HR foam core. A timeless upholstered set for residential, boutique hotel, and contract environments.',
    description_tr: 'Chester, beşinci düğme kapitone tasarımıdır — elle yerleştirilen düğmeler, elmas kapitone deseni ve derin HR köpük çekirdek. Konut, butik otel ve sözleşme ortamları için zamansız döşemeli set.',
    features: ['Hand button-tufted headboard', 'Diamond tufting pattern', 'Deep HR foam padding (10 cm)', 'Self-covered fabric buttons', 'Matched base construction'],
    features_tr: ['Elle düğme kapitoneli başlık', 'Elmas kapitone deseni', 'Derin HR köpük dolgu (10 cm)', 'Kumaşla kaplı düğmeler', 'Uyumlu taban yapısı'],
    specs: { 'Tufting': 'Hand-placed buttons', 'Pattern': 'Diamond', 'Core': 'HR35 foam + fibre', 'Buttons': 'Self-covered fabric', 'Sizes Available': 'Single to Super King' },
    specs_tr: { 'Kapitone': 'Elle yerleştirilen düğmeler', 'Desen': 'Elmas', 'Çekirdek': 'HR35 köpük + lif', 'Düğmeler': 'Kumaşla kaplı', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Button spacing', 'Headboard height', 'Custom dimensions'],
    fabrics: ['onyx', 'graphite', 'charcoal', 'midnight', 'carbon'],
    imageFile: '16_chester.jpg',
    featured: false,
  },
  {
    id: 'bb-17', name: 'Luxury',
    category: 'bed-base', subcategory: 'Premium', subcategory_tr: 'Premium',
    shortDesc: 'Top-tier luxury base with finest material specification.',
    shortDesc_tr: 'En yüksek malzeme spesifikasyonuyla üst düzey lüks taban.',
    description: 'The Luxury is the flagship Else Home bed base — the highest material specification, the most precise upholstery finishing, and complete customisation across every dimension. Engineered for five-star hotel suites and premium residential projects.',
    description_tr: 'Luxury, amiral Else Home yatak tabanıdır — en yüksek malzeme spesifikasyonu, en hassas döşeme kaplaması ve her boyutta tam özelleştirme. Beş yıldızlı otel süitleri ve premium konut projeleri için mühendislik anlayışıyla tasarlanmıştır.',
    features: ['Flagship material specification', 'Precision handcrafted upholstery', 'Full custom dimensions and fabrics', 'Luxury leg finish options', 'Five-star hospitality rated'],
    features_tr: ['Amiral malzeme spesifikasyonu', 'Hassas el yapımı döşeme', 'Tam özel boyutlar ve kumaşlar', 'Lüks ayak kaplama seçenekleri', 'Beş yıldızlı konaklama sertifikalı'],
    specs: { 'Grade': 'Flagship luxury', 'Construction': 'Premium hardwood + MDF', 'Upholstery': 'Hand-finished', 'Weight Capacity': '350 kg', 'Sizes Available': 'All sizes + bespoke' },
    specs_tr: { 'Sınıf': 'Amiral lüks', 'Yapı': 'Premium sert ahşap + MDF', 'Döşeme': 'El kaplamalı', 'Ağırlık Kapasitesi': '350 kg', 'Mevcut Boyutlar': 'Tüm boyutlar + özel' },
    customOptions: ['Premium fabric selection', 'Leg finish (chrome / brass / black)', 'Headboard specification', 'Bespoke dimensions'],
    fabrics: ['alabaster', 'linen', 'sand', 'onyx', 'stone'],
    imageFile: '17_luxury.jpg',
    featured: true,
  },
  {
    id: 'bb-18', name: 'Napoli',
    category: 'bed-base', subcategory: 'Continental', subcategory_tr: 'Kıta',
    shortDesc: 'European continental base with Italian-inspired elegance.',
    shortDesc_tr: 'İtalyan esinli zarafetiyle Avrupa kıta tipi taban.',
    description: 'The Napoli draws on Italian design sensibility — a full continental base with refined proportions, tapered chrome legs, and an upholstered deck. Precision-engineered for premium residential and five-star hospitality.',
    description_tr: 'Napoli, İtalyan tasarım anlayışından ilham alır — rafine oranlar, konik krom ayaklar ve döşemeli güverte ile tam kıta tipi taban. Premium konut ve beş yıldızlı konaklama için hassas mühendislikle üretilmiştir.',
    features: ['Continental construction', 'Tapered chrome legs (standard)', 'Upholstered top deck', 'Euro-specification frame', 'Optional storage configuration'],
    features_tr: ['Kıta tipi yapı', 'Konik krom ayaklar (standart)', 'Döşemeli üst güverte', 'Avrupa spesifikasyon çerçevesi', 'İsteğe bağlı depolama konfigürasyonu'],
    specs: { 'Type': 'Continental', 'Legs': 'Tapered chrome / brushed gold', 'Deck': 'Fully upholstered', 'Weight Capacity': '300 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Tür': 'Kıta tipi', 'Ayaklar': 'Konik krom / fırçalanmış altın', 'Güverte': 'Tam döşemeli', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg metal finish', 'Storage option', 'Custom dimensions'],
    fabrics: ['onyx', 'graphite', 'charcoal', 'midnight', 'carbon'],
    imageFile: '18_napoli.jpg',
    featured: false,
  },
  {
    id: 'bb-19', name: 'Paris',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Parisian-inspired upholstered base with refined proportions.',
    shortDesc_tr: 'Rafine oranlarıyla Paris esinli döşemeli taban.',
    description: 'The Paris brings a refined Parisian aesthetic to the Else Home range — soft upholstered proportions, elegant leg detail, and a headboard profile that references classic French interior design. Available in 40+ fabrics.',
    description_tr: 'Paris, Else Home aralığına rafine Paris estetiği kazandırır — yumuşak döşemeli oranlar, zarif ayak detayı ve klasik Fransız iç mekân tasarımına atıfta bulunan başlık profili. 40+ kumaşta mevcut.',
    features: ['Parisian-inspired silhouette', 'Elegant leg profile', 'Soft upholstered proportions', 'Solid hardwood frame', 'Full fabric selection available'],
    features_tr: ['Paris esinli siluet', 'Zarif ayak profili', 'Yumuşak döşemeli oranlar', 'Sağlam sert ahşap çerçeve', 'Tam kumaş seçimi mevcut'],
    specs: { 'Profile': 'French-inspired silhouette', 'Frame': 'Solid hardwood', 'Leg': 'Elegant detail finish', 'Weight Capacity': '280 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Profil': 'Fransız esinli siluet', 'Çerçeve': 'Sağlam sert ahşap', 'Ayak': 'Zarif detay kaplamı', 'Ağırlık Kapasitesi': '280 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg finish', 'Headboard height', 'Custom dimensions'],
    fabrics: ['linen', 'cream', 'sand', 'stone', 'charcoal', 'oyster'],
    imageFile: '19_paris.jpg',
    featured: false,
  },

  // ═══════════════════════════════════════════════════════
  // MATTRESSES  (6)
  // ═══════════════════════════════════════════════════════

  {
    id: 'mt-01', name: 'Foundation Pocket Spring',
    category: 'mattress', subcategory: 'Pocket Spring', subcategory_tr: 'Cep Yaylı',
    shortDesc: '1000-count hand-nested springs with natural fillings.',
    shortDesc_tr: '1000 sayım elle yuvalanmış yaylar, doğal dolgular.',
    description: '1000-count hand-nested pocket spring system with Belgian damask cover and traditional natural filling layers. A classic construction built with modern precision and available in custom spring counts.',
    description_tr: 'Belçika damas kılıfı ve geleneksel doğal dolgu katmanlarıyla 1000 sayım elle yuvalanmış cep yay sistemi. Modern hassasiyetle üretilmiş klasik yapı, özel yay sayılarında mevcut.',
    features: ['1000 hand-nested pocket springs', 'Belgian damask ticking', 'Natural wool and cotton fillings', 'Hand-tufted finish', 'Dual-sided turnover design'],
    features_tr: ['1000 elle yuvalanmış cep yay', 'Belçika damas kılıf', 'Doğal yün ve pamuk dolgu', 'Elle tutturulmuş kaplama', 'Çift taraflı çevrilebilir tasarım'],
    specs: { 'Spring Count': '1000 per 150 cm', 'Spring Type': 'Barrel pocket, hand-nested', 'Cover': 'Belgian damask', 'Fillings': 'Wool, cotton, coir', 'Depth': '24 cm' },
    specs_tr: { 'Yay Sayısı': '150 cm için 1000', 'Yay Tipi': 'Varil cep, elle yuvalanmış', 'Kılıf': 'Belçika damas', 'Dolgular': 'Yün, pamuk, koko', 'Derinlik': '24 cm' },
    customOptions: ['Spring count (800–2000)', 'Filling specification', 'Cover fabric selection', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Foundation+Pocket+Spring',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Foundation',
    featured: true,
    layers: [
      { label: 'Belgian Damask Ticking', color: '#f0edec' },
      { label: 'Natural Wool Layer', color: '#e8dcc8' },
      { label: 'Cotton Comfort Layer', color: '#f0e8d8' },
      { label: '1000 Pocket Spring System', color: '#d4cfc9' },
      { label: 'Coir Fibre Foundation', color: '#b8ae9a' },
      { label: 'Non-Woven Base', color: '#a09890' },
    ],
  },
  {
    id: 'mt-02', name: 'Dual Zone Pocket Spring',
    category: 'mattress', subcategory: 'Pocket Spring', subcategory_tr: 'Cep Yaylı',
    shortDesc: 'Five-zone spring mapping for ergonomic spinal support.',
    shortDesc_tr: 'Ergonomik omurga desteği için beş bölgeli yay haritalama.',
    description: 'A 5-zone pocket spring system with firmer lumbar support in the centre zones and softer shoulder support in the outer zones. Independent springs eliminate motion transfer between sleep partners.',
    description_tr: 'Merkez bölgelerde daha sert bel desteği ve dış bölgelerde daha yumuşak omuz desteği olan 5 bölgeli cep yay sistemi. Bağımsız yaylar uyku ortakları arasındaki hareket transferini ortadan kaldırır.',
    features: ['5-zone spring mapping', 'Firmer lumbar zone (centre)', 'Softer shoulder support (outer)', 'Motion isolation between zones', 'Breathable stretch-knit cover'],
    features_tr: ['5 bölgeli yay haritalama', 'Daha sert bel bölgesi (merkez)', 'Daha yumuşak omuz desteği (dış)', 'Bölgeler arası hareket izolasyonu', 'Nefes alabilir streç örgü kılıf'],
    specs: { 'Zones': '5-zone mapped', 'Lumbar Gauge': '1.4 mm steel', 'Shoulder Gauge': '1.0 mm steel', 'Cover': 'Stretch-knit', 'Depth': '26 cm' },
    specs_tr: { 'Bölgeler': '5 bölgeli haritalı', 'Bel Teli': '1,4 mm çelik', 'Omuz Teli': '1,0 mm çelik', 'Kılıf': 'Streç örgü', 'Derinlik': '26 cm' },
    customOptions: ['Zone configuration', 'Spring count per zone', 'Cover material', 'Comfort layer specification'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Dual+Zone+Pocket+Spring',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Dual+Zone',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-03', name: 'Contour Memory Foam',
    category: 'mattress', subcategory: 'Memory Foam', subcategory_tr: 'Visco Köpük',
    shortDesc: 'Four-layer CertiPUR-US memory foam construction.',
    shortDesc_tr: 'Dört katmanlı CertiPUR-US visco köpük yapısı.',
    description: 'A four-layer visco-elastic memory foam construction with open-cell technology for breathability. CertiPUR-US certified materials, cooling stretch-knit cover, and non-slip base fabric throughout.',
    description_tr: 'Nefes alabilirlik için açık hücreli teknolojiye sahip dört katmanlı visko-elastik bellek köpüğü yapısı. CertiPUR-US sertifikalı malzeme, soğutma streç örgü kılıf ve kaymaz taban kumaş.',
    features: ['4-layer construction', 'Open-cell visco-elastic foam', 'CertiPUR-US certified', 'Cooling stretch-knit cover', 'Non-slip base'],
    features_tr: ['4 katmanlı yapı', 'Açık hücreli visko-elastik köpük', 'CertiPUR-US sertifikalı', 'Soğutma streç örgü kılıf', 'Kaymaz taban'],
    specs: { 'Layers': 'Comfort + transition + support + cover', 'Top Layer': '3 cm visco-elastic (40 kg/m³)', 'Transition': '3 cm HR foam (35 kg/m³)', 'Support Base': '14 cm HR foam', 'Depth': '20 cm' },
    specs_tr: { 'Katmanlar': 'Konfor + geçiş + destek + kılıf', 'Üst Katman': '3 cm visko-elastik (40 kg/m³)', 'Geçiş': '3 cm HR köpük (35 kg/m³)', 'Destek Tabanı': '14 cm HR köpük', 'Derinlik': '20 cm' },
    customOptions: ['Layer specification', 'Foam density selection', 'Cover material', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Contour+Memory+Foam',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Contour',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-04', name: 'Arctic Gel Memory Foam',
    category: 'mattress', subcategory: 'Memory Foam', subcategory_tr: 'Visco Köpük',
    shortDesc: 'Gel-infused foam with phase-change cooling cover.',
    shortDesc_tr: 'Faz değiştiren soğutma kılıflı jel dolgulu köpük.',
    description: 'Gel-bead infused memory foam with a phase-change material cover. Active heat dissipation and breathable quilting make this the ideal specification for warm-climate markets and temperature-sensitive hotel environments.',
    description_tr: 'Faz değiştiren malzeme kılıflı jel boncuk dolgulu bellek köpüğü. Aktif ısı dağıtımı ve nefes alabilir kapitone, sıcak iklim pazarları ve sıcaklığa duyarlı otel ortamları için ideal spesifikasyon yapar.',
    features: ['Gel-bead infused top layer', 'Phase-change material cover', 'Active heat dissipation', 'Breathable quilted panel', 'Up to 3°C surface temperature reduction'],
    features_tr: ['Jel boncuk dolgulu üst katman', 'Faz değiştiren malzeme kılıf', 'Aktif ısı dağıtımı', 'Nefes alabilir kapitoneli panel', '3°C\'ye kadar yüzey sıcaklığı düşüşü'],
    specs: { 'Top Layer': '4 cm gel-infused (45 kg/m³)', 'Cover': 'PCM stretch-knit', 'Gel Type': 'Phase-change micro-encapsulated', 'Cooling': 'Up to −3°C surface', 'Depth': '22 cm' },
    specs_tr: { 'Üst Katman': '4 cm jel dolgulu (45 kg/m³)', 'Kılıf': 'PCM streç örgü', 'Jel Tipi': 'Faz değiştiren mikro kapsüllü', 'Soğutma': '−3°C\'ye kadar yüzey', 'Derinlik': '22 cm' },
    customOptions: ['Gel layer depth', 'PCM cover specification', 'Foam density', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Arctic+Gel+Memory+Foam',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Arctic+Gel',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-05', name: 'Natura Latex',
    category: 'mattress', subcategory: 'Latex', subcategory_tr: 'Lateks',
    shortDesc: '100% natural Talalay latex, OEKO-TEX certified.',
    shortDesc_tr: '%100 doğal Talalay lateks, OEKO-TEX sertifikalı.',
    description: '100% natural Talalay latex mattress with OEKO-TEX Standard 100 certification. Naturally hypoallergenic, sustainably sourced, open-cell pincore ventilation, and GOTS organic cotton cover.',
    description_tr: 'OEKO-TEX Standart 100 sertifikalı %100 doğal Talalay lateks yatak. Doğal olarak hipoalerjenik, sürdürülebilir kaynaklı, açık hücreli pincore havalandırma ve GOTS organik pamuk kılıf.',
    features: ['100% Talalay natural latex', 'OEKO-TEX Standard 100 certified', 'Naturally hypoallergenic', 'Open-cell pincore ventilation', 'GOTS organic cotton cover'],
    features_tr: ['%100 Talalay doğal lateks', 'OEKO-TEX Standart 100 sertifikalı', 'Doğal olarak hipoalerjenik', 'Açık hücreli pincore havalandırma', 'GOTS organik pamuk kılıf'],
    specs: { 'Material': '100% Talalay natural latex', 'Density': '75 kg/m³', 'Core': 'Pincore ventilated', 'Cover': 'GOTS organic cotton', 'Depth': '20 cm' },
    specs_tr: { 'Malzeme': '%100 Talalay doğal lateks', 'Yoğunluk': '75 kg/m³', 'Çekirdek': 'Pincore havalandırmalı', 'Kılıf': 'GOTS organik pamuk', 'Derinlik': '20 cm' },
    customOptions: ['Latex density (soft / medium / firm)', 'Cover material', 'Layer configuration', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Natura+Latex',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Natura',
    featured: true,
    layers: [],
  },
  {
    id: 'mt-06', name: 'Hybrid Elite',
    category: 'mattress', subcategory: 'Hybrid', subcategory_tr: 'Hibrit',
    shortDesc: 'Micro-coil base with memory foam comfort layer.',
    shortDesc_tr: 'Visco köpük konfor katmanlı mikro sarmal taban.',
    description: 'A 1200-count micro-coil support base combined with a visco-elastic memory foam comfort layer. The responsiveness of springs, the pressure relief of foam — in a single precision-engineered construction.',
    description_tr: '1200 sayım mikro sarmal destek tabanı, visko-elastik bellek köpüğü konfor katmanıyla birleştirilmiştir. Yayların duyarlılığı, köpüğün basınç giderimi — tek hassas mühendislik yapısında.',
    features: ['1200 micro-coils per 150 cm', 'Visco-elastic comfort layer', 'Zoned support construction', 'Breathable foam perimeter border', 'Knitted pillow-top cover'],
    features_tr: ['150 cm için 1200 mikro sarmal', 'Visko-elastik konfor katmanı', 'Bölgeli destek yapısı', 'Nefes alabilir köpük çevre bordürü', 'Örgülü yastık-üstü kılıf'],
    specs: { 'Coil Count': '1200 per 150 cm', 'Coil Height': '5 cm', 'Comfort Foam': '3 cm visco-elastic', 'Border': 'Breathable perimeter foam', 'Depth': '25 cm' },
    specs_tr: { 'Sarmal Sayısı': '150 cm için 1200', 'Sarmal Yüksekliği': '5 cm', 'Konfor Köpüğü': '3 cm visko-elastik', 'Bordür': 'Nefes alabilir çevre köpüğü', 'Derinlik': '25 cm' },
    customOptions: ['Coil count specification', 'Foam layer depth', 'Comfort level', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Hybrid+Elite',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Hybrid',
    featured: false,
    layers: [],
  },

  // ═══════════════════════════════════════════════════════
  // TOPPERS  (3)
  // ═══════════════════════════════════════════════════════

  {
    id: 'tp-01', name: 'Cloud Memory Topper',
    category: 'topper', subcategory: 'Memory Foam', subcategory_tr: 'Visco Köpük',
    shortDesc: '5 cm visco-elastic topper with cooling cover.',
    shortDesc_tr: 'Soğutma kılıflı 5 cm visco-elastik topper.',
    description: '5 cm visco-elastic memory foam topper (45 kg/m³) for mattress surface enhancement. Cooling stretch-knit cover, anti-slip base, and 4-point corner strap system. Machine-washable cover.',
    description_tr: 'Yatak yüzeyi iyileştirme için 5 cm visco-elastik bellek köpüğü topper (45 kg/m³). Soğutma streç örgü kılıf, kaymaz taban ve 4 köşe kayış sistemi. Makinede yıkanabilir kılıf.',
    features: ['5 cm visco-elastic foam (45 kg/m³)', 'Cooling stretch-knit cover', 'Anti-slip base fabric', '4-point corner strap system', 'Machine-washable removable cover'],
    features_tr: ['5 cm visco-elastik köpük (45 kg/m³)', 'Soğutma streç örgü kılıf', 'Kaymaz taban kumaş', '4 köşe kayış sistemi', 'Makinede yıkanabilir çıkarılabilir kılıf'],
    specs: { 'Foam': 'Visco-elastic (45 kg/m³)', 'Depth': '5 cm', 'Cover': 'Cooling stretch-knit', 'Base': 'Non-slip fabric', 'Straps': '4× adjustable corners' },
    specs_tr: { 'Köpük': 'Visco-elastik (45 kg/m³)', 'Derinlik': '5 cm', 'Kılıf': 'Soğutma streç örgü', 'Taban': 'Kaymaz kumaş', 'Kayışlar': '4× ayarlanabilir köşe' },
    customOptions: ['Foam density', 'Depth (3 / 5 / 7 cm)', 'Cover material', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Cloud+Memory+Topper',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Cloud+Topper',
    featured: false,
  },
  {
    id: 'tp-02', name: 'Natura Latex Topper',
    category: 'topper', subcategory: 'Latex', subcategory_tr: 'Lateks',
    shortDesc: 'Natural Dunlop latex topper with pincore ventilation.',
    shortDesc_tr: 'Pincore havalandırmalı doğal Dunlop lateks topper.',
    description: 'Natural Dunlop latex topper (65 kg/m³) with pincore ventilation and OEKO-TEX certification. Adds pressure-relief responsiveness and natural breathability to any mattress. GOTS organic cotton cover.',
    description_tr: 'Pincore havalandırma ve OEKO-TEX sertifikasıyla doğal Dunlop lateks topper (65 kg/m³). Herhangi bir yatak için basınç giderici duyarlılık ve doğal nefes alabilirlik ekler. GOTS organik pamuk kılıf.',
    features: ['Natural Dunlop process latex', 'Pincore ventilation pattern', 'OEKO-TEX certified', 'GOTS organic cotton cover', 'Elasticated anchor straps'],
    features_tr: ['Doğal Dunlop işlem lateksi', 'Pincore havalandırma deseni', 'OEKO-TEX sertifikalı', 'GOTS organik pamuk kılıf', 'Elastikli sabitleme kayışları'],
    specs: { 'Material': 'Natural Dunlop latex', 'Density': '65 kg/m³', 'Depth': '4 cm', 'Cover': 'GOTS organic cotton', 'Ventilation': 'Pincore pattern' },
    specs_tr: { 'Malzeme': 'Doğal Dunlop lateks', 'Yoğunluk': '65 kg/m³', 'Derinlik': '4 cm', 'Kılıf': 'GOTS organik pamuk', 'Havalandırma': 'Pincore desen' },
    customOptions: ['Latex density', 'Depth (3 / 4 / 6 cm)', 'Cover selection', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Natura+Latex+Topper',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Latex+Topper',
    featured: false,
  },
  {
    id: 'tp-03', name: 'Wool & Cotton Topper',
    category: 'topper', subcategory: 'Natural Fibre', subcategory_tr: 'Doğal Lif',
    shortDesc: 'Pure British wool topper with cotton cambric casing.',
    shortDesc_tr: 'Pamuk kambrik kılıflı saf İngiliz yünü topper.',
    description: 'Pure British wool fill encased in cotton cambric — a natural temperature-regulating topper ideal for hotel and contract environments. 400 gsm standard fill weight. Machine washable at 40°C.',
    description_tr: 'Pamuk kambriğe sarılmış saf İngiliz yünü dolgu — otel ve sözleşme ortamları için ideal doğal sıcaklık düzenleyici topper. 400 gsm standart dolgu ağırlığı. 40°C\'de makine yıkama.',
    features: ['Pure British wool fill', '400 gsm fill weight standard', 'Cotton cambric 180TC outer', 'Temperature-regulating year-round', 'Machine washable at 40°C'],
    features_tr: ['Saf İngiliz yünü dolgu', '400 gsm dolgu ağırlığı standart', 'Pamuk kambrik 180TC dış kılıf', 'Yıl boyu sıcaklık düzenleyici', '40°C\'de makine yıkama'],
    specs: { 'Fill': 'Pure British wool', 'Fill Weight': '400 gsm', 'Casing': 'Cotton cambric 180TC', 'Depth': '3 cm', 'Wash': 'Machine wash 40°C' },
    specs_tr: { 'Dolgu': 'Saf İngiliz yünü', 'Dolgu Ağırlığı': '400 gsm', 'Kılıf': 'Pamuk kambrik 180TC', 'Derinlik': '3 cm', 'Yıkama': '40°C makine yıkama' },
    customOptions: ['Fill weight (300 / 400 / 500 gsm)', 'Casing thread count', 'Dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Wool+%26+Cotton+Topper',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Wool+Topper',
    featured: false,
  },
];

const categoryPlaceholders = {
  'bed-base': {
    image: 'brand_assets/placeholders/bed-base-main.svg',
    thumb: 'brand_assets/placeholders/bed-base-thumb.svg',
  },
  mattress: {
    image: 'brand_assets/placeholders/mattress-main.svg',
    thumb: 'brand_assets/placeholders/mattress-thumb.svg',
  },
  topper: {
    image: 'brand_assets/placeholders/topper-main.svg',
    thumb: 'brand_assets/placeholders/topper-thumb.svg',
  },
};

function applyProductImages(seedProducts) {
  return seedProducts.map(product => {
    const fallback = categoryPlaceholders[product.category] || {};
    const folder   = `images/products/${product.category}/`;
    const file     = product.imageFile || `${product.id}-main.jpg`;
    const imgSrc   = `${folder}${file}`;
    const baseName = file.replace(/\.[^.]+$/, '');
    return {
      ...product,
      image:         imgSrc,
      thumb:         imgSrc,
      imageFolder:   folder,
      imageBaseName: baseName,
      imageFallback: fallback.image || '',
    };
  });
}

const products = applyProductImages(baseProducts);

// ═══════════════════════════════════════════════════════
// FABRIC PALETTE
// ═══════════════════════════════════════════════════════

const fabrics = {
  alabaster:    { name: 'Alabaster',       hex: '#F2EDE4', group: 'neutral' },
  linen:        { name: 'Natural Linen',   hex: '#D8CAB0', group: 'neutral' },
  oyster:       { name: 'Oyster',          hex: '#E8DFD0', group: 'neutral' },
  cream:        { name: 'Warm Cream',      hex: '#F0E8D8', group: 'neutral' },
  ecru:         { name: 'Écru',            hex: '#EDE4D3', group: 'neutral' },
  biscuit:      { name: 'Biscuit',         hex: '#D4B896', group: 'neutral' },
  ivory:        { name: 'Ivory',           hex: '#FAFAF5', group: 'neutral' },
  sand:         { name: 'Desert Sand',     hex: '#C8A87A', group: 'warm'    },
  camel:        { name: 'Camel',           hex: '#B8934A', group: 'warm'    },
  cognac:       { name: 'Cognac',          hex: '#9B5E3A', group: 'warm'    },
  clay:         { name: 'Clay',            hex: '#A87060', group: 'warm'    },
  taupe:        { name: 'Taupe',           hex: '#9E907C', group: 'neutral' },
  stone:        { name: 'Stone',           hex: '#B8B0A8', group: 'cool'    },
  mist:         { name: 'Dove Mist',       hex: '#C8CDD4', group: 'cool'    },
  sage:         { name: 'Sage Green',      hex: '#8A9E8B', group: 'cool'    },
  slate:        { name: 'Slate Blue',      hex: '#7B8FA1', group: 'cool'    },
  ocean:        { name: 'Ocean',           hex: '#4A6E8A', group: 'cool'    },
  forest:       { name: 'Forest',          hex: '#4A6249', group: 'cool'    },
  storm:        { name: 'Storm Grey',      hex: '#6A7280', group: 'cool'    },
  pewter:       { name: 'Pewter',          hex: '#8A8E94', group: 'cool'    },
  graphite:     { name: 'Graphite',        hex: '#4A4E54', group: 'dark'    },
  charcoal:     { name: 'Charcoal',        hex: '#3A3D42', group: 'dark'    },
  midnight:     { name: 'Midnight Blue',   hex: '#1B2C4A', group: 'dark'    },
  'navy-fabric':{ name: 'Deep Navy',       hex: '#03163D', group: 'dark'    },
  onyx:         { name: 'Onyx',            hex: '#2C2C2C', group: 'dark'    },
  ebony:        { name: 'Ebony',           hex: '#1E1E1E', group: 'dark'    },
  anthracite:   { name: 'Anthracite',      hex: '#2D3032', group: 'dark'    },
  carbon:       { name: 'Carbon',          hex: '#383838', group: 'dark'    },
};

// ═══════════════════════════════════════════════════════
// CATEGORIES
// ═══════════════════════════════════════════════════════

const categories = [
  {
    id: 'bed-base',
    name: 'Bed Base Systems',
    name_tr: 'Yatak Taban Sistemleri',
    count: 19,
    description: 'Platform, storage, ottoman, adjustable, wingback, and divan bases — engineered for export markets, hotel contracts, and premium residential use.',
    description_tr: 'Platform, depolama, ottoman, ayarlanabilir, kanat arkalıklı ve divan tabanlar — ihracat pazarları, otel sözleşmeleri ve premium konut projeleri için mühendislik anlayışıyla üretilmiştir.',
    image: 'https://placehold.co/800x600/f0edec/03163D?text=Bed+Base+Systems',
  },
  {
    id: 'mattress',
    name: 'Mattresses',
    name_tr: 'Matraslar',
    count: 6,
    description: 'Pocket spring, memory foam, latex, and hybrid mattresses built to custom specifications for every comfort requirement.',
    description_tr: 'Her konfor gereksinimi için özel spesifikasyona göre üretilen cep yaylı, visco köpük, lateks ve hibrit matraslar.',
    image: 'https://placehold.co/800x600/e5e2e1/03163D?text=Mattresses',
  },
  {
    id: 'topper',
    name: 'Toppers',
    name_tr: 'Topperlar',
    count: 3,
    description: 'Memory foam, natural latex, and wool topper systems for mattress enhancement and hotel bedding programmes.',
    description_tr: 'Matrası iyileştirme ve otel yatak programları için visco köpük, doğal lateks ve yün topper sistemleri.',
    image: 'https://placehold.co/800x600/dcd9d9/03163D?text=Toppers',
  },
];

// ═══════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════

function getProductById(id) {
  return products.find(p => p.id === id) || null;
}

function getProductsByCategory(cat) {
  return products.filter(p => p.category === cat);
}

function getFeaturedProducts() {
  return products.filter(p => p.featured);
}

function getFabric(id) {
  return fabrics[id] || { name: id, hex: '#ccc', group: 'neutral' };
}

function getRelated(product, limit = 4) {
  return products
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}

if (typeof window !== 'undefined') {
  window.ElseHomeData = {
    products,
    categories,
    fabrics,
    getProductById,
    getProductsByCategory,
    getFeaturedProducts,
    getFabric,
    getRelated,
  };
}
