// Else Home — Product Data
//
// PRODUCT IMAGES: Add photos to images/products/
//   Bed bases: use imageFile field (e.g. '1_aura_xxl.jpg')
//   Mattresses / toppers: name as [id]-main.jpg (e.g. mt-01-main.jpg)
//   Missing images fall back to the brand_assets placeholder for that category.

const baseProducts = [

  // ═══════════════════════════════════════════════════════
  // BED BASE SETS  (19)
  // ═══════════════════════════════════════════════════════

  {
    id: 'bb-01', name: 'Aura XXL',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Oversized upholstered bed base with premium fabric finish.',
    shortDesc_tr: 'Büyük boy döşemeli yatak tabanı, premium kumaş kaplama.',
    description: 'The Aura XXL delivers a bold, oversized silhouette engineered for specification-led interiors. Full-perimeter upholstery, a solid hardwood subframe, and 40+ fabric options across all sizes.',
    description_tr: 'Aura XXL, spesifikasyon odaklı projeler için geliştirilmiş cesur ve büyük ölçekli bir siluet sunar. Tam çevre döşeme, sağlam sert ahşap alt çerçeve ve tüm ölçülerde 40+ kumaş seçeneğiyle üretilir.',
    features: ['Solid hardwood subframe', 'Full-perimeter precision upholstery', 'Oversized XXL proportions', 'Custom dimensions on request', 'Contract-grade materials throughout'],
    features_tr: ['Sağlam sert ahşap alt çerçeve', 'Tam çevre hassas döşeme', 'Büyük boy XXL oranlar', 'Talep üzerine özel boyutlar', 'Yüksek dayanımlı malzemeler'],
    specs: { 'Construction': 'Solid hardwood + MDF composite', 'Upholstery': 'Full fabric coverage', 'Standard Leg Height': '28 cm', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Yapı': 'Sağlam sert ahşap + MDF kompozit', 'Döşeme': 'Tam kumaş kaplama', 'Standart Ayak Yüksekliği': '28 cm', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height adjustment', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'oyster', 'slate', 'onyx', 'mist'],
    imageFile: '1_aura_xxl.jpg',
    featured: true,
  },
  {
    id: 'bb-02', name: 'Berlin',
    category: 'headboard', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Architectural platform base with clean geometric lines.',
    shortDesc_tr: 'Temiz geometrik hatlarıyla mimari platform taban.',
    description: 'The Berlin is a refined platform base with strict geometric proportions and flush edge detailing. A solid hardwood frame, full upholstery, and a hidden leg system deliver a clean contemporary profile.',
    description_tr: 'Berlin, net geometrik oranları ve düz kenar detaylarıyla rafine bir platform bazadır. Sağlam sert ahşap çerçeve, tam döşeme ve gizli ayak sistemiyle çağdaş bir görünüm sunar.',
    features: ['Solid hardwood structural frame', 'Flush edge finishing', 'Hidden leg system', 'Matching headboard range', 'Custom dimensions available'],
    features_tr: ['Sağlam sert ahşap yapısal çerçeve', 'Düz kenar kaplama', 'Gizli ayak sistemi', 'Uyumlu başlık aralığı', 'Özel boyutlar mevcut'],
    specs: { 'Construction': 'Engineered hardwood + MDF', 'Upholstery': 'Full perimeter', 'Weight Capacity': '280 kg', 'Leg Height': 'Adjustable', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Yapı': 'Mühendislik sert ahşap + MDF', 'Döşeme': 'Tam çevre', 'Ağırlık Kapasitesi': '280 kg', 'Ayak Yüksekliği': 'Ayarlanabilir', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg height adjustment', 'Headboard integration', 'Custom dimensions'],
    fabrics: ['sand', 'sage', 'storm', 'charcoal', 'oyster', 'cream'],
    imageFile: '2_berlin.jpg',
    featured: false,
  },
  {
    id: 'bb-03', name: 'Metropolis',
    category: 'headboard', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Statement platform base designed for large-scale production.',
    shortDesc_tr: 'Büyük ölçekli üretim için tasarlanmış iddialı platform baza.',
    description: 'The Metropolis is engineered for projects that demand scale and presence. Robust solid hardwood construction, a deep upholstery profile, and a broad platform deck give it a confident architectural stance.',
    description_tr: 'Metropolis, ölçek ve güçlü görünüm isteyen projeler için geliştirilmiştir. Sağlam sert ahşap yapı, derin döşeme profili ve geniş platform yüzeyiyle mimari bir duruş sunar.',
    features: ['Broad platform deck profile', 'Solid hardwood frame', 'Full-perimeter upholstery', 'Contract-grade durability', 'Custom fabric and dimensions'],
    features_tr: ['Geniş platform güverte profili', 'Sağlam sert ahşap çerçeve', 'Tam çevre döşeme', 'Sözleşme kaliteli dayanıklılık', 'Özel kumaş ve boyutlar'],
    specs: { 'Construction': 'Solid hardwood + composite', 'Deck Width': 'Extended platform', 'Weight Capacity': '320 kg', 'Upholstery': 'Full coverage', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Yapı': 'Sağlam sert ahşap + kompozit', 'Güverte Genişliği': 'Geniş platform', 'Ağırlık Kapasitesi': '320 kg', 'Döşeme': 'Tam kaplama', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Deck height', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['ivory', 'anthracite', 'camel', 'forest', 'stone', 'charcoal'],
    imageFile: '3_metropolis.jpg',
    featured: true,
  },
  {
    id: 'bb-04', name: 'Perla XXL',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Luxury oversized base with refined upholstery detailing.',
    shortDesc_tr: 'Rafine döşeme detaylarıyla lüks büyük boy taban.',
    description: 'The Perla XXL combines oversized proportions with meticulous upholstery finishing. Piped or plain edge detail options, deep HR foam padding, and a solid hardwood frame create a premium made-to-order base.',
    description_tr: 'Perla XXL, büyük boy oranları titiz döşeme işçiliğiyle birleştirir. Borulu veya düz kenar seçenekleri, derin HR köpük dolgu ve sağlam sert ahşap çerçevesiyle premium bir özel üretim baza sunar.',
    features: ['Oversized XXL construction', 'Piped or plain edge detailing', 'Deep HR foam padding', 'Solid hardwood frame', 'Contract-grade fabric throughout'],
    features_tr: ['Büyük boy XXL yapı', 'Borulu veya düz kenar detay', 'Derin HR köpük dolgu', 'Sağlam sert ahşap çerçeve', 'Yüksek kaliteli kumaş uygulaması'],
    specs: { 'Set Includes': 'Base + optional headboard', 'Padding': '8 cm HR foam', 'Edge Detail': 'Piped or plain', 'Weight Capacity': '300 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Set İçeriği': 'Taban + isteğe bağlı başlık', 'Dolgu': '8 cm HR köpük', 'Kenar Detayı': 'Borulu veya düz', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Edge detailing (piped / plain)', 'Headboard height', 'Custom dimensions'],
    fabrics: ['ecru', 'cognac', 'pewter', 'midnight', 'ivory', 'oyster'],
    imageFile: '4_perla_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-05', name: 'Business Class',
    category: 'headboard', subcategory: 'Premium', subcategory_tr: 'Premium',
    shortDesc: 'High-durability premium base built for repeatable production.',
    shortDesc_tr: 'Tekrarlanabilir üretim için geliştirilmiş yüksek dayanımlı premium baza.',
    description: 'The Business Class is built for demanding daily use with a reinforced hardwood frame, heavy-duty upholstery construction, and precision manufacturing to exact specification.',
    description_tr: 'Business Class, yoğun günlük kullanım için güçlendirilmiş sert ahşap çerçeve, dayanıklı döşeme yapısı ve tam spesifikasyona göre hassas üretim anlayışıyla geliştirilmiştir.',
    features: ['Reinforced hardwood frame', 'Heavy-duty upholstery construction', 'Anti-sag perimeter support', 'High-durability build standard', 'Custom dimensions and fabrics'],
    features_tr: ['Güçlendirilmiş sert ahşap çerçeve', 'Dayanıklı döşeme yapısı', 'Sarkmayı önleyici çevre desteği', 'Yüksek dayanım standardı', 'Özel boyutlar ve kumaşlar'],
    specs: { 'Construction': 'Reinforced hardwood', 'Upholstery Grade': 'Contract-rated', 'Weight Capacity': '350 kg', 'Durability': '10+ year rated', 'Sizes Available': 'Single to Super King' },
    specs_tr: { 'Yapı': 'Güçlendirilmiş sert ahşap', 'Döşeme Sınıfı': 'Sözleşme sertifikalı', 'Ağırlık Kapasitesi': '350 kg', 'Dayanıklılık': '10+ yıl sertifikalı', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Headboard style', 'Leg finish', 'Custom dimensions'],
    fabrics: ['cream', 'mist', 'slate', 'onyx', 'charcoal', 'stone'],
    imageFile: '5_business_class.jpg',
    featured: true,
  },
  {
    id: 'bb-06', name: 'Chester XXL',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Oversized Chester-style base with deep button tufting.',
    shortDesc_tr: 'Derin düğme kapitoneli büyük boy Chester tarzı taban.',
    description: 'The Chester XXL delivers the iconic deeply tufted aesthetic at oversized scale. Hand-placed button tufting, 12 cm HR foam padding, and a solid hardwood frame create a statement piece with technical depth.',
    description_tr: 'Chester XXL, ikonik derin kapitone görünümü büyük ölçekte sunar. Elle yerleştirilen düğmeler, 12 cm HR köpük dolgu ve sağlam sert ahşap çerçeveyle teknik derinliği yüksek, iddialı bir ürün ortaya çıkar.',
    features: ['Hand button-tufted finish', 'Oversized XXL proportions', '12 cm deep HR foam padding', 'Diamond tufting pattern', 'Solid hardwood frame'],
    features_tr: ['Elle düğme kapitone kaplama', 'Büyük boy XXL oranlar', '12 cm derin HR köpük dolgu', 'Elmas kapitone deseni', 'Sağlam sert ahşap çerçeve'],
    specs: { 'Tufting': 'Hand-placed buttons', 'Padding': '12 cm HR foam + fibre', 'Buttons': 'Self-covered fabric', 'Frame': 'Solid hardwood', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Kapitone': 'Elle yerleştirilen düğmeler', 'Dolgu': '12 cm HR köpük + lif', 'Düğmeler': 'Kumaşla kaplı', 'Çerçeve': 'Sağlam sert ahşap', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Button spacing', 'Tufting pattern', 'Custom dimensions'],
    fabrics: ['oyster', 'biscuit', 'taupe', 'graphite', 'sand', 'ecru'],
    imageFile: '6_chester_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-07', name: 'Dormo XXL',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Wide-format upholstered base with wraparound profile.',
    shortDesc_tr: 'Çevreleyen profilli geniş formatlı döşemeli taban.',
    description: 'The Dormo XXL features a wraparound upholstered profile with an extended footboard design. It is built for interiors where scale, comfort, and visual continuity define the space.',
    description_tr: 'Dormo XXL, uzatılmış ayak ucu tasarımıyla çevreleyen bir döşemeli profile sahiptir. Ölçek, konfor ve görsel bütünlüğün öne çıktığı mekanlar için geliştirilmiştir.',
    features: ['Wraparound upholstered profile', 'Extended footboard design', 'Oversized XXL format', 'Solid hardwood subframe', 'Full custom fabric options'],
    features_tr: ['Çevreleyen döşemeli profil', 'Uzatılmış ayak tahtası tasarımı', 'Büyük boy XXL format', 'Sağlam sert ahşap alt çerçeve', 'Tam özel kumaş seçenekleri'],
    specs: { 'Profile': 'Wraparound upholstered', 'Frame': 'Solid hardwood', 'Weight Capacity': '300 kg', 'Upholstery': 'Full perimeter + footboard', 'Sizes Available': 'King to Super King + Custom' },
    specs_tr: { 'Profil': 'Çevreleyen döşemeli', 'Çerçeve': 'Sağlam sert ahşap', 'Ağırlık Kapasitesi': '300 kg', 'Döşeme': 'Tam çevre + ayak tahtası', 'Mevcut Boyutlar': 'King\'den Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Footboard height', 'Leg finish', 'Custom dimensions'],
    fabrics: ['sand', 'ocean', 'clay', 'carbon', 'cream', 'ivory'],
    imageFile: '7_dormo_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-08', name: 'Elize XXL',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Sculptural oversized base with refined edge profile.',
    shortDesc_tr: 'Rafine kenar profilli heykelsi büyük boy taban.',
    description: 'The Elize XXL combines sculptural form with precision upholstery. A distinctive edge profile, deep-padded construction, and oversized format make it a signature product for high-end interiors.',
    description_tr: 'Elize XXL, heykelsi formu hassas döşemeyle birleştirir. Belirgin kenar profili, derin dolgulu yapısı ve büyük boy formatıyla üst segment projeler için imza bir üründür.',
    features: ['Distinctive sculpted edge profile', 'Deep-padded construction', 'Oversized XXL proportions', 'Contract-grade materials', 'Custom fabric and dimensions'],
    features_tr: ['Belirgin heykelsi kenar profili', 'Derin dolgulu yapı', 'Büyük boy XXL oranlar', 'Sözleşme kaliteli malzeme', 'Özel kumaş ve boyutlar'],
    specs: { 'Profile': 'Sculpted edge', 'Padding': '10 cm HR foam', 'Frame': 'Solid hardwood composite', 'Weight Capacity': '300 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Profil': 'Heykelsi kenar', 'Dolgu': '10 cm HR köpük', 'Çerçeve': 'Sağlam sert ahşap kompozit', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Edge profile depth', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['ivory', 'stone', 'slate', 'charcoal', 'onyx'],
    imageFile: '8_elize_xxl.jpg',
    featured: false,
  },
  {
    id: 'bb-09', name: 'Genova',
    category: 'headboard', subcategory: 'Continental', subcategory_tr: 'Kıta',
    shortDesc: 'Continental base with elegant tapered leg detail.',
    shortDesc_tr: 'Zarif konik ayak detaylı kıta tipi taban.',
    description: 'The Genova is a full continental base featuring an elegant tapered leg system and clean upholstered deck. Precision engineering keeps the design understated, balanced, and adaptable.',
    description_tr: 'Genova, zarif konik ayak sistemi ve temiz döşemeli yüzeyiyle tam kıta tipi bir bazadır. Hassas mühendisliği sayesinde sade, dengeli ve uyarlanabilir bir tasarım sunar.',
    features: ['Tapered leg detail', 'Full continental construction', 'Clean upholstered deck', 'Euro-specification frame', 'Matching headboard available'],
    features_tr: ['Konik ayak detayı', 'Tam kıta tipi yapı', 'Temiz döşemeli güverte', 'Avrupa spesifikasyon çerçevesi', 'Uyumlu başlık mevcut'],
    specs: { 'Type': 'Continental', 'Legs': 'Tapered euro-specification', 'Deck': 'Fully upholstered', 'Weight Capacity': '280 kg', 'Sizes Available': 'Double to Super King' },
    specs_tr: { 'Tür': 'Kıta tipi', 'Ayaklar': 'Konik Avrupa spesifikasyonu', 'Güverte': 'Tam döşemeli', 'Ağırlık Kapasitesi': '280 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Leg finish', 'Headboard style', 'Custom dimensions'],
    fabrics: ['ivory', 'cream', 'oyster', 'ecru', 'alabaster'],
    imageFile: '9_genova.jpg',
    featured: false,
  },
  {
    id: 'bb-10', name: 'Maladive',
    category: 'headboard', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Low-slung platform base with wide, relaxed proportions.',
    shortDesc_tr: 'Resort esinli oranlarla alçak profilli platform taban.',
    description: 'The Maladive is a low-slung platform base with floor-level proportions, full upholstery, and clean-line construction that create a relaxed yet refined aesthetic.',
    description_tr: 'Maladive, zemin seviyesine yakın oranları, tam döşemesi ve temiz hatlı yapısıyla rahat ama rafine bir estetik sunan alçak profilli bir platform bazadır.',
    features: ['Low floor-level profile', 'Full-perimeter upholstery', 'Resort-spec construction', 'Custom dimensions available', 'Matching headboard range'],
    features_tr: ['Alçak zemin seviyesi profil', 'Tam çevre döşeme', 'Resort spesifikasyon yapısı', 'Özel boyutlar mevcut', 'Uyumlu başlık aralığı'],
    specs: { 'Floor Clearance': '14 cm', 'Upholstery': 'Full coverage', 'Frame': 'Engineered hardwood', 'Weight Capacity': '280 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Zemin Mesafesi': '14 cm', 'Döşeme': 'Tam kaplama', 'Çerçeve': 'Mühendislik sert ahşap', 'Ağırlık Kapasitesi': '280 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg height', 'Headboard integration', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'sand', 'onyx', 'stone'],
    imageFile: '10_maladive.jpg',
    featured: false,
  },
  {
    id: 'bb-11', name: 'Venus',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Curved upholstered base with soft-form silhouette.',
    shortDesc_tr: 'Yumuşak form siluetli eğri döşemeli taban.',
    description: 'The Venus introduces a soft-form curved silhouette to the Else Home range. Precision upholstery over a curved hardwood frame creates an organic and highly refined aesthetic.',
    description_tr: 'Venus, Else Home koleksiyonuna yumuşak formlu kıvrımlı bir siluet kazandırır. Eğri sert ahşap çerçeve üzerindeki hassas döşeme, organik ve rafine bir görünüm oluşturur.',
    features: ['Curved hardwood frame', 'Soft-form upholstered silhouette', 'Full fabric coverage', 'Custom fabric selection', 'Matching headboard available'],
    features_tr: ['Eğri sert ahşap çerçeve', 'Yumuşak formlu döşemeli siluet', 'Tam kumaş kaplama', 'Özel kumaş seçimi', 'Uyumlu başlık mevcut'],
    specs: { 'Frame': 'Curved solid hardwood', 'Profile': 'Soft-form silhouette', 'Weight Capacity': '280 kg', 'Upholstery': 'Full curved coverage', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Çerçeve': 'Eğri sağlam sert ahşap', 'Profil': 'Yumuşak form siluet', 'Ağırlık Kapasitesi': '280 kg', 'Döşeme': 'Tam eğri kaplama', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Curve radius', 'Headboard style', 'Custom dimensions'],
    fabrics: ['charcoal', 'slate', 'stone', 'onyx', 'graphite'],
    imageFile: '11_venus.jpg',
    featured: false,
  },
  {
    id: 'bb-12', name: 'Lounge',
    category: 'headboard', subcategory: 'Ottoman', subcategory_tr: 'Ottoman',
    shortDesc: 'Deep-lounging ottoman base with full-access storage.',
    shortDesc_tr: 'Tam erişimli depolama ile derin dinlenme ottoman tabanı.',
    description: 'The Lounge combines deep, reclined proportions with full-access ottoman storage. A heavy-duty gas-lift mechanism, waterproof interior lining, and 40+ fabric options make it practical and highly configurable.',
    description_tr: 'Lounge, derin dinlenme oranlarını tam erişimli sandıklı depolamayla birleştirir. Dayanıklı gaz kaldırma mekanizması, su geçirmez iç astarı ve 40+ kumaş seçeneğiyle hem işlevsel hem de yüksek ölçüde özelleştirilebilirdir.',
    features: ['Full-access gas-lift storage', 'Deep lounge proportions', 'Waterproof interior lining', 'Heavy-duty gas pistons', 'Contract-grade construction'],
    features_tr: ['Tam genişlikte erişimli gaz kaldırma deposu', 'Derin dinlenme oranlar', 'Su geçirmez iç astar', 'Ağır hizmet gaz pistonları', 'Sözleşme kaliteli yapı'],
    specs: { 'Opening': 'Full-width access', 'Storage Depth': '30 cm', 'Mechanism': 'Gas-lift pistons', 'Lining': 'Waterproof non-woven', 'Sizes Available': 'King to Super King + Custom' },
    specs_tr: { 'Açılış': 'Tam genişlik erişimi', 'Depolama Derinliği': '30 cm', 'Mekanizma': 'Gaz kaldırma pistonları', 'Astar': 'Su geçirmez dokusuz kumaş', 'Mevcut Boyutlar': 'King\'den Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Opening direction', 'Interior lining', 'Custom dimensions'],
    fabrics: ['ivory', 'cream', 'oyster', 'ecru', 'alabaster'],
    imageFile: '12_lounge.jpg',
    featured: false,
  },
  {
    id: 'bb-13', name: 'Aura',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Classic Aura upholstered base — timeless proportions.',
    shortDesc_tr: 'Klasik Aura döşemeli taban — zamansız oranlar.',
    description: 'The original Aura features clean upholstered proportions, a solid hardwood frame, and full fabric coverage. A versatile base available in all standard sizes and 40+ fabrics.',
    description_tr: 'Orijinal Aura, temiz döşemeli oranları, sağlam sert ahşap çerçevesi ve tam kumaş kaplamasıyla öne çıkar. Tüm standart ölçülerde ve 40+ kumaş seçeneğiyle sunulan çok yönlü bir bazadır.',
    features: ['Solid hardwood subframe', 'Full-perimeter upholstery', 'Clean proportional design', 'Custom dimensions on request', 'Contract-grade materials'],
    features_tr: ['Sağlam sert ahşap alt çerçeve', 'Tam çevre döşeme', 'Temiz orantısal tasarım', 'Talep üzerine özel boyutlar', 'Sözleşme kaliteli malzeme'],
    specs: { 'Construction': 'Solid hardwood + MDF', 'Upholstery': 'Full fabric coverage', 'Leg Height': '28 cm standard', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Yapı': 'Sağlam sert ahşap + MDF', 'Döşeme': 'Tam kumaş kaplama', 'Ayak Yüksekliği': '28 cm standart', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height adjustment', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['linen', 'navy-fabric', 'stone', 'ebony', 'cream'],
    imageFile: '13_aura.jpg',
    featured: false,
  },
  {
    id: 'bb-14', name: 'California',
    category: 'headboard', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Wide-deck platform base with California proportions.',
    shortDesc_tr: 'California oranlarıyla geniş güverteli platform taban.',
    description: 'The California takes its name from its generous width-to-height ratio — a wide, low platform deck that commands space. Solid hardwood construction, full upholstery, and custom sizing for all non-standard bed dimensions.',
    description_tr: 'California adını geniş yükseklik-genişlik oranından alır — alanı yöneten geniş, alçak platform güvertesi. Sağlam sert ahşap yapı, tam döşeme ve tüm standart dışı yatak boyutları için özel boyut.',
    features: ['Wide platform deck proportions', 'Low-profile design', 'Solid hardwood frame', 'Full-perimeter upholstery', 'Custom sizing available'],
    features_tr: ['Geniş platform güverte oranları', 'Alçak profil tasarımı', 'Sağlam sert ahşap çerçeve', 'Tam çevre döşeme', 'Özel boyutlandırma mevcut'],
    specs: { 'Profile': 'Wide low-platform', 'Construction': 'Solid hardwood', 'Weight Capacity': '300 kg', 'Upholstery': 'Full coverage', 'Sizes Available': 'California King + All Custom' },
    specs_tr: { 'Profil': 'Geniş alçak platform', 'Yapı': 'Sağlam sert ahşap', 'Ağırlık Kapasitesi': '300 kg', 'Döşeme': 'Tam kaplama', 'Mevcut Boyutlar': 'California King + Tüm Özel' },
    customOptions: ['Fabric selection', 'Deck height', 'Headboard integration', 'Custom dimensions'],
    fabrics: ['slate', 'charcoal', 'stone', 'graphite'],
    imageFile: '14_california.jpg',
    featured: false,
  },
  {
    id: 'bb-15', name: 'Chepau',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Distinctive upholstered base with signature profile.',
    shortDesc_tr: 'İmza profilli belirgin döşemeli taban.',
    description: 'The Chepau is a signature Else Home design with precise panel proportions and refined edge detail. It pairs a distinctive profile with robust construction and flexible customisation.',
    description_tr: 'Chepau, hassas panel oranları ve rafine kenar detayıyla Else Home’un imza tasarımlarından biridir. Belirgin profili, sağlam yapısı ve esnek özelleştirme seçenekleriyle öne çıkar.',
    features: ['Signature panel proportions', 'Refined edge detailing', 'Solid hardwood frame', 'Full precision upholstery', 'Custom fabric and dimensions'],
    features_tr: ['İmza panel oranları', 'Rafine kenar detayı', 'Sağlam sert ahşap çerçeve', 'Tam hassas döşeme', 'Özel kumaş ve boyutlar'],
    specs: { 'Profile': 'Signature panel design', 'Frame': 'Solid hardwood', 'Weight Capacity': '300 kg', 'Upholstery': 'Full perimeter', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Profil': 'İmza panel tasarımı', 'Çerçeve': 'Sağlam sert ahşap', 'Ağırlık Kapasitesi': '300 kg', 'Döşeme': 'Tam çevre', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Panel detail', 'Headboard pairing', 'Custom dimensions'],
    fabrics: ['onyx', 'slate', 'graphite', 'midnight', 'stone', 'charcoal'],
    imageFile: '15_chepau.jpg',
    featured: false,
  },
  {
    id: 'bb-16', name: 'Chester',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Classic Chester button-tufted base and headboard set.',
    shortDesc_tr: 'Klasik Chester düğme kapitoneli taban ve başlık seti.',
    description: 'The Chester is the quintessential button-tufted design with hand-placed buttons, a diamond tufting pattern, and a deep HR foam core. A timeless upholstered set with strong visual identity.',
    description_tr: 'Chester, elle yerleştirilen düğmeleri, elmas kapitone deseni ve derin HR köpük çekirdeğiyle klasik kapitone anlayışını yansıtır. Güçlü görsel kimliğe sahip zamansız bir döşemeli settir.',
    features: ['Hand button-tufted headboard', 'Diamond tufting pattern', 'Deep HR foam padding (10 cm)', 'Self-covered fabric buttons', 'Matched base construction'],
    features_tr: ['Elle düğme kapitoneli başlık', 'Elmas kapitone deseni', 'Derin HR köpük dolgu (10 cm)', 'Kumaşla kaplı düğmeler', 'Uyumlu taban yapısı'],
    specs: { 'Tufting': 'Hand-placed buttons', 'Pattern': 'Diamond', 'Core': 'HR35 foam + fibre', 'Buttons': 'Self-covered fabric', 'Sizes Available': 'Single to Super King' },
    specs_tr: { 'Kapitone': 'Elle yerleştirilen düğmeler', 'Desen': 'Elmas', 'Çekirdek': 'HR35 köpük + lif', 'Düğmeler': 'Kumaşla kaplı', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Button spacing', 'Headboard height', 'Custom dimensions'],
    fabrics: ['onyx', 'graphite', 'charcoal', 'midnight', 'carbon'],
    imageFile: '16_chester.jpg',
    featured: false,
  },
  {
    id: 'bb-17', name: 'Luxury',
    category: 'headboard', subcategory: 'Premium', subcategory_tr: 'Premium',
    shortDesc: 'Top-tier luxury base with finest material specification.',
    shortDesc_tr: 'En yüksek malzeme spesifikasyonuyla üst düzey lüks taban.',
    description: 'The Luxury is the flagship Else Home bed base with top-tier material specification, highly precise upholstery finishing, and complete customisation across every dimension.',
    description_tr: 'Luxury, en üst düzey malzeme spesifikasyonu, son derece hassas döşeme işçiliği ve her ölçüde tam özelleştirme sunan amiral Else Home bazasıdır.',
    features: ['Flagship material specification', 'Precision handcrafted upholstery', 'Full custom dimensions and fabrics', 'Luxury leg finish options', 'Premium build standard'],
    features_tr: ['Amiral malzeme spesifikasyonu', 'Hassas el işçiliği döşeme', 'Tam özel boyutlar ve kumaşlar', 'Lüks ayak kaplama seçenekleri', 'Premium yapı standardı'],
    specs: { 'Grade': 'Flagship luxury', 'Construction': 'Premium hardwood + MDF', 'Upholstery': 'Hand-finished', 'Weight Capacity': '350 kg', 'Sizes Available': 'All sizes + bespoke' },
    specs_tr: { 'Sınıf': 'Amiral lüks', 'Yapı': 'Premium sert ahşap + MDF', 'Döşeme': 'El kaplamalı', 'Ağırlık Kapasitesi': '350 kg', 'Mevcut Boyutlar': 'Tüm boyutlar + özel' },
    customOptions: ['Premium fabric selection', 'Leg finish (chrome / brass / black)', 'Headboard specification', 'Bespoke dimensions'],
    fabrics: ['alabaster', 'linen', 'sand', 'onyx', 'stone'],
    imageFile: '17_luxury.jpg',
    featured: true,
  },
  {
    id: 'bb-18', name: 'Napoli',
    category: 'headboard', subcategory: 'Continental', subcategory_tr: 'Kıta',
    shortDesc: 'European continental base with Italian-inspired elegance.',
    shortDesc_tr: 'İtalyan esinli zarafetiyle Avrupa kıta tipi taban.',
    description: 'The Napoli draws on Italian design sensibility with refined proportions, tapered chrome legs, and an upholstered deck. Precision engineering keeps the silhouette elegant and structurally balanced.',
    description_tr: 'Napoli, rafine oranları, konik krom ayakları ve döşemeli yüzeyiyle İtalyan tasarım anlayışından ilham alır. Hassas mühendisliği sayesinde zarif ve yapısal olarak dengeli bir siluet sunar.',
    features: ['Continental construction', 'Tapered chrome legs (standard)', 'Upholstered top deck', 'Euro-specification frame', 'Optional storage configuration'],
    features_tr: ['Kıta tipi yapı', 'Konik krom ayaklar (standart)', 'Döşemeli üst güverte', 'Avrupa spesifikasyon çerçevesi', 'İsteğe bağlı depolama konfigürasyonu'],
    specs: { 'Type': 'Continental', 'Legs': 'Tapered chrome / brushed gold', 'Deck': 'Fully upholstered', 'Weight Capacity': '300 kg', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Tür': 'Kıta tipi', 'Ayaklar': 'Konik krom / fırçalanmış altın', 'Güverte': 'Tam döşemeli', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg metal finish', 'Storage option', 'Custom dimensions'],
    fabrics: ['onyx', 'graphite', 'charcoal', 'midnight', 'carbon'],
    imageFile: '18_napoli.jpg',
    featured: false,
  },
  {
    id: 'bb-19', name: 'Paris',
    category: 'headboard', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Parisian-inspired upholstered base with refined proportions.',
    shortDesc_tr: 'Rafine oranlarıyla Paris esinli döşemeli taban.',
    description: 'The Paris brings a refined Parisian aesthetic to the Else Home range — soft upholstered proportions, elegant leg detail, and a headboard profile that references classic French interior design. Available in 40+ fabrics.',
    description_tr: 'Paris, Else Home aralığına rafine Paris estetiği kazandırır — yumuşak döşemeli oranlar, zarif ayak detayı ve klasik Fransız iç mekân tasarımına atıfta bulunan başlık profili. 40+ kumaşta mevcut.',
    features: ['Parisian-inspired silhouette', 'Elegant leg profile', 'Soft upholstered proportions', 'Solid hardwood frame', 'Full fabric selection available'],
    features_tr: ['Paris esinli siluet', 'Zarif ayak profili', 'Yumuşak döşemeli oranlar', 'Sağlam sert ahşap çerçeve', 'Tam kumaş seçimi mevcut'],
    specs: { 'Profile': 'French-inspired silhouette', 'Frame': 'Solid hardwood', 'Leg': 'Elegant detail finish', 'Weight Capacity': '280 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Profil': 'Fransız esinli siluet', 'Çerçeve': 'Sağlam sert ahşap', 'Ayak': 'Zarif detay kaplamı', 'Ağırlık Kapasitesi': '280 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection', 'Leg finish', 'Headboard height', 'Custom dimensions'],
    fabrics: ['linen', 'cream', 'sand', 'stone', 'charcoal', 'oyster'],
    imageFile: '19_paris.jpg',
    featured: false,
  },

  // ═══════════════════════════════════════════════════════
  // MATTRESSES  (6)
  // ═══════════════════════════════════════════════════════

  {
    id: 'mt-01', name: 'Foundation Pocket Spring',
    category: 'mattress', subcategory: 'Pocket Spring', subcategory_tr: 'Cep Yaylı',
    shortDesc: '1000-count hand-nested springs with natural fillings.',
    shortDesc_tr: '1000 sayım elle yuvalanmış yaylar, doğal dolgular.',
    description: '1000-count hand-nested pocket spring system with Belgian damask cover and traditional natural filling layers. A classic construction built with modern precision and available in custom spring counts.',
    description_tr: 'Belçika damas kılıfı ve geleneksel doğal dolgu katmanlarıyla 1000 sayım elle yuvalanmış cep yay sistemi. Modern hassasiyetle üretilmiş klasik yapı, özel yay sayılarında mevcut.',
    features: ['1000 hand-nested pocket springs', 'Belgian damask ticking', 'Natural wool and cotton fillings', 'Hand-tufted finish', 'Dual-sided turnover design'],
    features_tr: ['1000 elle yuvalanmış cep yay', 'Belçika damas kılıf', 'Doğal yün ve pamuk dolgu', 'Elle tutturulmuş kaplama', 'Çift taraflı çevrilebilir tasarım'],
    specs: { 'Spring Count': '1000 per 150 cm', 'Spring Type': 'Barrel pocket, hand-nested', 'Cover': 'Belgian damask', 'Fillings': 'Wool, cotton, coir', 'Depth': '24 cm' },
    specs_tr: { 'Yay Sayısı': '150 cm için 1000', 'Yay Tipi': 'Varil cep, elle yuvalanmış', 'Kılıf': 'Belçika damas', 'Dolgular': 'Yün, pamuk, koko', 'Derinlik': '24 cm' },
    customOptions: ['Spring count (800–2000)', 'Filling specification', 'Cover fabric selection', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Foundation+Pocket+Spring',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Foundation',
    featured: true,
    layers: [
      { label: 'Belgian Damask Ticking', color: '#f0edec' },
      { label: 'Natural Wool Layer', color: '#e8dcc8' },
      { label: 'Cotton Comfort Layer', color: '#f0e8d8' },
      { label: '1000 Pocket Spring System', color: '#d4cfc9' },
      { label: 'Coir Fibre Foundation', color: '#b8ae9a' },
      { label: 'Non-Woven Base', color: '#a09890' },
    ],
  },
  {
    id: 'mt-02', name: 'Dual Zone Pocket Spring',
    category: 'mattress', subcategory: 'Pocket Spring', subcategory_tr: 'Cep Yaylı',
    shortDesc: 'Five-zone spring mapping for ergonomic spinal support.',
    shortDesc_tr: 'Ergonomik omurga desteği için beş bölgeli yay haritalama.',
    description: 'A 5-zone pocket spring system with firmer lumbar support in the centre zones and softer shoulder support in the outer zones. Independent springs eliminate motion transfer between sleep partners.',
    description_tr: 'Merkez bölgelerde daha sert bel desteği ve dış bölgelerde daha yumuşak omuz desteği olan 5 bölgeli cep yay sistemi. Bağımsız yaylar uyku ortakları arasındaki hareket transferini ortadan kaldırır.',
    features: ['5-zone spring mapping', 'Firmer lumbar zone (centre)', 'Softer shoulder support (outer)', 'Motion isolation between zones', 'Breathable stretch-knit cover'],
    features_tr: ['5 bölgeli yay haritalama', 'Daha sert bel bölgesi (merkez)', 'Daha yumuşak omuz desteği (dış)', 'Bölgeler arası hareket izolasyonu', 'Nefes alabilir streç örgü kılıf'],
    specs: { 'Zones': '5-zone mapped', 'Lumbar Gauge': '1.4 mm steel', 'Shoulder Gauge': '1.0 mm steel', 'Cover': 'Stretch-knit', 'Depth': '26 cm' },
    specs_tr: { 'Bölgeler': '5 bölgeli haritalı', 'Bel Teli': '1,4 mm çelik', 'Omuz Teli': '1,0 mm çelik', 'Kılıf': 'Streç örgü', 'Derinlik': '26 cm' },
    customOptions: ['Zone configuration', 'Spring count per zone', 'Cover material', 'Comfort layer specification'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Dual+Zone+Pocket+Spring',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Dual+Zone',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-03', name: 'Contour Memory Foam',
    category: 'mattress', subcategory: 'Memory Foam', subcategory_tr: 'Visco Köpük',
    shortDesc: 'Four-layer CertiPUR-US memory foam construction.',
    shortDesc_tr: 'Dört katmanlı CertiPUR-US visco köpük yapısı.',
    description: 'A four-layer visco-elastic memory foam construction with open-cell technology for breathability. CertiPUR-US certified materials, cooling stretch-knit cover, and non-slip base fabric throughout.',
    description_tr: 'Nefes alabilirlik için açık hücreli teknolojiye sahip dört katmanlı visko-elastik bellek köpüğü yapısı. CertiPUR-US sertifikalı malzeme, soğutma streç örgü kılıf ve kaymaz taban kumaş.',
    features: ['4-layer construction', 'Open-cell visco-elastic foam', 'CertiPUR-US certified', 'Cooling stretch-knit cover', 'Non-slip base'],
    features_tr: ['4 katmanlı yapı', 'Açık hücreli visko-elastik köpük', 'CertiPUR-US sertifikalı', 'Soğutma streç örgü kılıf', 'Kaymaz taban'],
    specs: { 'Layers': 'Comfort + transition + support + cover', 'Top Layer': '3 cm visco-elastic (40 kg/m³)', 'Transition': '3 cm HR foam (35 kg/m³)', 'Support Base': '14 cm HR foam', 'Depth': '20 cm' },
    specs_tr: { 'Katmanlar': 'Konfor + geçiş + destek + kılıf', 'Üst Katman': '3 cm visko-elastik (40 kg/m³)', 'Geçiş': '3 cm HR köpük (35 kg/m³)', 'Destek Tabanı': '14 cm HR köpük', 'Derinlik': '20 cm' },
    customOptions: ['Layer specification', 'Foam density selection', 'Cover material', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Contour+Memory+Foam',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Contour',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-04', name: 'Arctic Gel Memory Foam',
    category: 'mattress', subcategory: 'Memory Foam', subcategory_tr: 'Visco Köpük',
    shortDesc: 'Gel-infused foam with phase-change cooling cover.',
    shortDesc_tr: 'Faz değiştiren soğutma kılıflı jel dolgulu köpük.',
    description: 'Gel-bead infused memory foam with a phase-change material cover. Active heat dissipation and breathable quilting make this an ideal specification for warm climates and temperature-sensitive users.',
    description_tr: 'Faz değiştiren malzeme kılıflı jel boncuk dolgulu bellek köpüğü. Aktif ısı dağıtımı ve nefes alabilir kapitone, sıcak iklimler ve ısıya duyarlı kullanıcılar için ideal bir spesifikasyon sunar.',
    features: ['Gel-bead infused top layer', 'Phase-change material cover', 'Active heat dissipation', 'Breathable quilted panel', 'Up to 3°C surface temperature reduction'],
    features_tr: ['Jel boncuk dolgulu üst katman', 'Faz değiştiren malzeme kılıf', 'Aktif ısı dağıtımı', 'Nefes alabilir kapitoneli panel', '3°C\'ye kadar yüzey sıcaklığı düşüşü'],
    specs: { 'Top Layer': '4 cm gel-infused (45 kg/m³)', 'Cover': 'PCM stretch-knit', 'Gel Type': 'Phase-change micro-encapsulated', 'Cooling': 'Up to −3°C surface', 'Depth': '22 cm' },
    specs_tr: { 'Üst Katman': '4 cm jel dolgulu (45 kg/m³)', 'Kılıf': 'PCM streç örgü', 'Jel Tipi': 'Faz değiştiren mikro kapsüllü', 'Soğutma': '−3°C\'ye kadar yüzey', 'Derinlik': '22 cm' },
    customOptions: ['Gel layer depth', 'PCM cover specification', 'Foam density', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Arctic+Gel+Memory+Foam',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Arctic+Gel',
    featured: false,
    layers: [],
  },
  {
    id: 'mt-05', name: 'Natura Latex',
    category: 'mattress', subcategory: 'Latex', subcategory_tr: 'Lateks',
    shortDesc: '100% natural Talalay latex, OEKO-TEX certified.',
    shortDesc_tr: '%100 doğal Talalay lateks, OEKO-TEX sertifikalı.',
    description: '100% natural Talalay latex mattress with OEKO-TEX Standard 100 certification. Naturally hypoallergenic, sustainably sourced, open-cell pincore ventilation, and GOTS organic cotton cover.',
    description_tr: 'OEKO-TEX Standart 100 sertifikalı %100 doğal Talalay lateks yatak. Doğal olarak hipoalerjenik, sürdürülebilir kaynaklı, açık hücreli pincore havalandırma ve GOTS organik pamuk kılıf.',
    features: ['100% Talalay natural latex', 'OEKO-TEX Standard 100 certified', 'Naturally hypoallergenic', 'Open-cell pincore ventilation', 'GOTS organic cotton cover'],
    features_tr: ['%100 Talalay doğal lateks', 'OEKO-TEX Standart 100 sertifikalı', 'Doğal olarak hipoalerjenik', 'Açık hücreli pincore havalandırma', 'GOTS organik pamuk kılıf'],
    specs: { 'Material': '100% Talalay natural latex', 'Density': '75 kg/m³', 'Core': 'Pincore ventilated', 'Cover': 'GOTS organic cotton', 'Depth': '20 cm' },
    specs_tr: { 'Malzeme': '%100 Talalay doğal lateks', 'Yoğunluk': '75 kg/m³', 'Çekirdek': 'Pincore havalandırmalı', 'Kılıf': 'GOTS organik pamuk', 'Derinlik': '20 cm' },
    customOptions: ['Latex density (soft / medium / firm)', 'Cover material', 'Layer configuration', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Natura+Latex',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Natura',
    featured: true,
    layers: [],
  },
  {
    id: 'mt-06', name: 'Hybrid Elite',
    category: 'mattress', subcategory: 'Hybrid', subcategory_tr: 'Hibrit',
    shortDesc: 'Micro-coil base with memory foam comfort layer.',
    shortDesc_tr: 'Visco köpük konfor katmanlı mikro sarmal taban.',
    description: 'A 1200-count micro-coil support base combined with a visco-elastic memory foam comfort layer. The responsiveness of springs, the pressure relief of foam — in a single precision-engineered construction.',
    description_tr: '1200 sayım mikro sarmal destek tabanı, visko-elastik bellek köpüğü konfor katmanıyla birleştirilmiştir. Yayların duyarlılığı, köpüğün basınç giderimi — tek hassas mühendislik yapısında.',
    features: ['1200 micro-coils per 150 cm', 'Visco-elastic comfort layer', 'Zoned support construction', 'Breathable foam perimeter border', 'Knitted pillow-top cover'],
    features_tr: ['150 cm için 1200 mikro sarmal', 'Visko-elastik konfor katmanı', 'Bölgeli destek yapısı', 'Nefes alabilir köpük çevre bordürü', 'Örgülü yastık-üstü kılıf'],
    specs: { 'Coil Count': '1200 per 150 cm', 'Coil Height': '5 cm', 'Comfort Foam': '3 cm visco-elastic', 'Border': 'Breathable perimeter foam', 'Depth': '25 cm' },
    specs_tr: { 'Sarmal Sayısı': '150 cm için 1200', 'Sarmal Yüksekliği': '5 cm', 'Konfor Köpüğü': '3 cm visko-elastik', 'Bordür': 'Nefes alabilir çevre köpüğü', 'Derinlik': '25 cm' },
    customOptions: ['Coil count specification', 'Foam layer depth', 'Comfort level', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Hybrid+Elite',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Hybrid',
    featured: false,
    layers: [],
  },

  // ═══════════════════════════════════════════════════════
  // TOPPERS  (3)
  // ═══════════════════════════════════════════════════════

  {
    id: 'tp-01', name: 'Cloud Memory Topper',
    category: 'topper', subcategory: 'Memory Foam', subcategory_tr: 'Visco Köpük',
    shortDesc: '5 cm visco-elastic topper with cooling cover.',
    shortDesc_tr: 'Soğutma kılıflı 5 cm visco-elastik ped.',
    description: '5 cm visco-elastic memory foam topper (45 kg/m³) for mattress surface enhancement. Cooling stretch-knit cover, anti-slip base, and a 4-point corner strap system. Machine-washable cover.',
    description_tr: 'Yatak yüzeyini desteklemek için geliştirilmiş 5 cm visco-elastik bellek köpüğü ped (45 kg/m³). Soğutma streç örgü kılıf, kaymaz taban ve 4 köşeli sabitleme sistemi içerir. Kılıfı makinede yıkanabilir.',
    features: ['5 cm visco-elastic foam (45 kg/m³)', 'Cooling stretch-knit cover', 'Anti-slip base fabric', '4-point corner strap system', 'Machine-washable removable cover'],
    features_tr: ['5 cm visco-elastik köpük (45 kg/m³)', 'Soğutma streç örgü kılıf', 'Kaymaz taban kumaş', '4 köşe kayış sistemi', 'Makinede yıkanabilir çıkarılabilir kılıf'],
    specs: { 'Foam': 'Visco-elastic (45 kg/m³)', 'Depth': '5 cm', 'Cover': 'Cooling stretch-knit', 'Base': 'Non-slip fabric', 'Straps': '4× adjustable corners' },
    specs_tr: { 'Köpük': 'Visco-elastik (45 kg/m³)', 'Derinlik': '5 cm', 'Kılıf': 'Soğutma streç örgü', 'Taban': 'Kaymaz kumaş', 'Kayışlar': '4× ayarlanabilir köşe' },
    customOptions: ['Foam density', 'Depth (3 / 5 / 7 cm)', 'Cover material', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/f0edec/03163D?text=Cloud+Memory+Topper',
    thumb: 'https://placehold.co/600x450/f0edec/03163D?text=Cloud+Topper',
    featured: false,
  },
  {
    id: 'tp-02', name: 'Natura Latex Topper',
    category: 'topper', subcategory: 'Latex', subcategory_tr: 'Lateks',
    shortDesc: 'Natural Dunlop latex topper with pincore ventilation.',
    shortDesc_tr: 'Pincore havalandırmalı doğal Dunlop lateks ped.',
    description: 'Natural Dunlop latex topper (65 kg/m³) with pincore ventilation and OEKO-TEX certification. Adds pressure-relief responsiveness and natural breathability to any mattress. GOTS organic cotton cover.',
    description_tr: 'Pincore havalandırma ve OEKO-TEX sertifikasıyla doğal Dunlop lateks ped (65 kg/m³). Her yatakta basınç azaltıcı esneklik ve doğal nefes alabilirlik sağlar. GOTS organik pamuk kılıfla tamamlanır.',
    features: ['Natural Dunlop process latex', 'Pincore ventilation pattern', 'OEKO-TEX certified', 'GOTS organic cotton cover', 'Elasticated anchor straps'],
    features_tr: ['Doğal Dunlop işlem lateksi', 'Pincore havalandırma deseni', 'OEKO-TEX sertifikalı', 'GOTS organik pamuk kılıf', 'Elastikli sabitleme kayışları'],
    specs: { 'Material': 'Natural Dunlop latex', 'Density': '65 kg/m³', 'Depth': '4 cm', 'Cover': 'GOTS organic cotton', 'Ventilation': 'Pincore pattern' },
    specs_tr: { 'Malzeme': 'Doğal Dunlop lateks', 'Yoğunluk': '65 kg/m³', 'Derinlik': '4 cm', 'Kılıf': 'GOTS organik pamuk', 'Havalandırma': 'Pincore desen' },
    customOptions: ['Latex density', 'Depth (3 / 4 / 6 cm)', 'Cover selection', 'Custom dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/e5e2e1/03163D?text=Natura+Latex+Topper',
    thumb: 'https://placehold.co/600x450/e5e2e1/03163D?text=Latex+Topper',
    featured: false,
  },
  {
    id: 'tp-03', name: 'Wool & Cotton Topper',
    category: 'topper', subcategory: 'Natural Fibre', subcategory_tr: 'Doğal Lif',
    shortDesc: 'Pure British wool topper with cotton cambric casing.',
    shortDesc_tr: 'Pamuk kambrik kılıflı saf İngiliz yünü ped.',
    description: 'Pure British wool fill encased in cotton cambric creates a naturally temperature-regulating topper with a 400 gsm standard fill weight. Machine washable at 40°C.',
    description_tr: 'Pamuk kambrik içine alınmış saf İngiliz yünü dolgu, doğal sıcaklık dengesi sağlayan bir ped oluşturur. 400 gsm standart dolgu ağırlığına sahiptir ve 40°C’de makinede yıkanabilir.',
    features: ['Pure British wool fill', '400 gsm fill weight standard', 'Cotton cambric 180TC outer', 'Temperature-regulating year-round', 'Machine washable at 40°C'],
    features_tr: ['Saf İngiliz yünü dolgu', '400 gsm dolgu ağırlığı standart', 'Pamuk kambrik 180TC dış kılıf', 'Yıl boyu sıcaklık düzenleyici', '40°C\'de makine yıkama'],
    specs: { 'Fill': 'Pure British wool', 'Fill Weight': '400 gsm', 'Casing': 'Cotton cambric 180TC', 'Depth': '3 cm', 'Wash': 'Machine wash 40°C' },
    specs_tr: { 'Dolgu': 'Saf İngiliz yünü', 'Dolgu Ağırlığı': '400 gsm', 'Kılıf': 'Pamuk kambrik 180TC', 'Derinlik': '3 cm', 'Yıkama': '40°C makine yıkama' },
    customOptions: ['Fill weight (300 / 400 / 500 gsm)', 'Casing thread count', 'Dimensions'],
    fabrics: [],
    image: 'https://placehold.co/1200x900/dcd9d9/03163D?text=Wool+%26+Cotton+Topper',
    thumb: 'https://placehold.co/600x450/dcd9d9/03163D?text=Wool+Topper',
    featured: false,
  },

  // ── BED BASES  (6) ─────────────────────────────────────────

  {
    id: 'bb-20', name: 'Adjustable Base',
    category: 'bed-base', subcategory: 'Adjustable', subcategory_tr: 'Ayarlanabilir',
    shortDesc: 'Motorised adjustable base with head and foot articulation.',
    shortDesc_tr: 'Kafa ve ayak hareketlendirmeli motorlu ayarlanabilir baza.',
    description: 'A motorised adjustable base with independent head and foot articulation. Available in split configurations for dual-user control. Solid steel frame with whisper-quiet motor system and wireless remote.',
    description_tr: 'Bağımsız kafa ve ayak hareketlendirmeli motorlu ayarlanabilir baza. Çift kullanıcı kontrolü için bölünmüş konfigürasyonda da mevcuttur. Sessiz motor sistemi ve kablosuz kumandayla sağlam çelik çerçeve.',
    features: ['Head and foot independent articulation', 'Whisper-quiet motor system', 'Wireless remote control', 'Split king configuration available', 'Custom dimensions on request'],
    features_tr: ['Bağımsız kafa ve ayak hareketlendirmesi', 'Sessiz motor sistemi', 'Kablosuz kumanda', 'Bölünmüş king konfigürasyonu mevcut', 'Talep üzerine özel boyutlar'],
    specs: { 'Frame': 'Solid steel', 'Motor': 'Whisper-quiet DC', 'Control': 'Wireless remote', 'Articulation': 'Head + foot independent', 'Sizes Available': 'Single / King Split / Super King Split' },
    specs_tr: { 'Çerçeve': 'Sağlam çelik', 'Motor': 'Sessiz DC motor', 'Kontrol': 'Kablosuz kumanda', 'Hareketlendirme': 'Kafa + ayak bağımsız', 'Mevcut Boyutlar': 'Tek / King Bölünmüş / Süper King Bölünmüş' },
    customOptions: ['Split configuration', 'Motor speed setting', 'USB charging ports', 'Under-bed lighting'],
    fabrics: [],
    imageFile: 'adjustable_base_1.jpg',
    featured: true,
  },
  {
    id: 'bb-21', name: 'Box Base',
    category: 'bed-base', subcategory: 'Platform', subcategory_tr: 'Platform',
    shortDesc: 'Solid box platform base with upholstered top surface.',
    shortDesc_tr: 'Döşemeli üst yüzeyli sağlam kutu platform baza.',
    description: 'A solid box platform base with a clean rectangular profile and fully upholstered top surface. Engineered hardwood construction throughout. Available in all standard sizes and custom dimensions.',
    description_tr: 'Temiz dikdörtgen profilli ve tamamen döşemeli üst yüzeyli sağlam kutu platform baza. Boydan boya mühendislik sert ahşap yapı. Tüm standart ölçülerde ve özel boyutlarda mevcuttur.',
    features: ['Solid box profile', 'Fully upholstered top surface', 'Engineered hardwood frame', '40+ fabric options', 'Custom dimensions available'],
    features_tr: ['Sağlam kutu profili', 'Tamamen döşemeli üst yüzey', 'Mühendislik sert ahşap çerçeve', '40+ kumaş seçeneği', 'Özel boyutlar mevcut'],
    specs: { 'Frame': 'Engineered hardwood', 'Top Surface': 'Fully upholstered', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom', 'Fabric': '40+ options' },
    specs_tr: { 'Çerçeve': 'Mühendislik sert ahşap', 'Üst Yüzey': 'Tam döşemeli', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel', 'Kumaş': '40+ seçenek' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'oyster', 'charcoal', 'onyx', 'slate'],
    imageFile: 'box_base_1.jpg',
    featured: false,
  },
  {
    id: 'bb-22', name: 'Box Spring Base',
    category: 'bed-base', subcategory: 'Divan', subcategory_tr: 'Divan',
    shortDesc: 'Traditional divan with open-coil spring interior.',
    shortDesc_tr: 'Açık sarmal yaylı iç yapılı geleneksel divan baza.',
    description: 'A traditional divan base with an open-coil spring interior for added mattress support and ventilation. Fabric-covered timber frame with castors or fixed legs. Available in full or split divan configuration.',
    description_tr: 'Ek yatak desteği ve havalandırma için açık sarmal yaylı iç yapılı geleneksel divan baza. Tekerlek veya sabit ayaklı kumaş kaplı ahşap çerçeve. Tam veya bölünmüş divan konfigürasyonunda mevcuttur.',
    features: ['Open-coil spring interior', 'Fabric-covered timber frame', 'Castor or fixed leg options', 'Full or split configuration', 'Custom dimensions available'],
    features_tr: ['Açık sarmal yaylı iç yapı', 'Kumaş kaplı ahşap çerçeve', 'Tekerlek veya sabit ayak seçenekleri', 'Tam veya bölünmüş konfigürasyon', 'Özel boyutlar mevcut'],
    specs: { 'Interior': 'Open-coil springs', 'Frame': 'Timber + hardboard', 'Base': 'Castor or fixed legs', 'Configuration': 'Full or split divan', 'Sizes Available': 'Single to Super King' },
    specs_tr: { 'İç Yapı': 'Açık sarmal yaylar', 'Çerçeve': 'Ahşap + sert karton', 'Taban': 'Tekerlek veya sabit ayaklar', 'Konfigürasyon': 'Tam veya bölünmüş divan', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e' },
    customOptions: ['Fabric selection', 'Castor or fixed legs', 'Split or full divan', 'Custom dimensions'],
    fabrics: ['alabaster', 'cream', 'stone', 'graphite', 'charcoal'],
    imageFile: 'box_spring_base_1.jpg',
    featured: false,
  },
  {
    id: 'bb-23', name: 'Storage Base',
    category: 'bed-base', subcategory: 'Ottoman', subcategory_tr: 'Ottoman',
    shortDesc: 'Full-access ottoman storage base with gas-lift mechanism.',
    shortDesc_tr: 'Gaz kaldırma mekanizmalı tam erişimli ottoman depolama bazası.',
    description: 'A full-access ottoman storage base with heavy-duty gas-lift pistons and a waterproof non-woven interior lining. Side or end opening available. Solid hardwood frame with full upholstery in 40+ fabrics.',
    description_tr: 'Ağır hizmet gaz kaldırma pistonlu ve su geçirmez dokusuz kumaş iç astarlı tam erişimli ottoman depolama bazası. Yandan veya ayak ucundan açılış seçeneği mevcut. 40+ kumaşta tam döşemeli sağlam sert ahşap çerçeve.',
    features: ['Full-access gas-lift storage', 'Heavy-duty gas pistons', 'Waterproof interior lining', 'Side or end opening options', '40+ fabric selection'],
    features_tr: ['Tam erişimli gaz kaldırma deposu', 'Ağır hizmet gaz pistonları', 'Su geçirmez iç astar', 'Yandan veya ayak ucundan açılış', '40+ kumaş seçimi'],
    specs: { 'Mechanism': 'Gas-lift pistons', 'Opening': 'Side or end — full width', 'Storage Depth': '30 cm', 'Lining': 'Waterproof non-woven', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Mekanizma': 'Gaz kaldırma pistonları', 'Açılış': 'Yandan veya ayak ucu — tam genişlik', 'Depolama Derinliği': '30 cm', 'Astar': 'Su geçirmez dokusuz kumaş', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Opening direction (side / end)', 'Interior lining colour', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'oyster', 'slate', 'graphite', 'onyx'],
    imageFile: 'storage_base_1.jpg',
    featured: true,
  },
  {
    id: 'bb-24', name: 'Opened from Side Base',
    category: 'bed-base', subcategory: 'Ottoman', subcategory_tr: 'Ottoman',
    shortDesc: 'Side-opening ottoman base with full-width storage access.',
    shortDesc_tr: 'Tam genişlikte depolama erişimli yandan açılan ottoman baza.',
    description: 'An ottoman storage base with a dedicated side-opening mechanism for environments where end-lift access is not practical. Heavy-duty gas pistons, full-width storage cavity, and waterproof lining. Suitable for hotel and hospitality projects.',
    description_tr: 'Ayak ucu kaldırma erişiminin pratik olmadığı ortamlar için özel yandan açılan mekanizmalı ottoman depolama bazası. Ağır hizmet gaz pistonları, tam genişlikte depolama boşluğu ve su geçirmez astar. Otel ve konaklama projeleri için uygundur.',
    features: ['Side-opening gas-lift mechanism', 'Full-width storage cavity', 'Waterproof interior lining', 'Hospitality-grade construction', 'Custom dimensions available'],
    features_tr: ['Yandan açılan gaz kaldırma mekanizması', 'Tam genişlikte depolama boşluğu', 'Su geçirmez iç astar', 'Otelcilik sınıfı yapı', 'Özel boyutlar mevcut'],
    specs: { 'Opening': 'Side-opening only', 'Mechanism': 'Gas-lift pistons', 'Storage Depth': '28 cm', 'Lining': 'Waterproof non-woven', 'Sizes Available': 'Double to Super King + Custom' },
    specs_tr: { 'Açılış': 'Yalnızca yandan açılış', 'Mekanizma': 'Gaz kaldırma pistonları', 'Depolama Derinliği': '28 cm', 'Astar': 'Su geçirmez dokusuz kumaş', 'Mevcut Boyutlar': 'Çift kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Interior lining colour', 'Custom dimensions'],
    fabrics: ['alabaster', 'cream', 'stone', 'charcoal', 'onyx', 'slate'],
    imageFile: 'opened_from_side_base_1.jpg',
    featured: false,
  },
  {
    id: 'bb-25', name: 'Rounded Base',
    category: 'bed-base', subcategory: 'Upholstered', subcategory_tr: 'Döşemeli',
    shortDesc: 'Soft-form upholstered base with rounded corner profile.',
    shortDesc_tr: 'Yuvarlatılmış köşe profilli yumuşak formlu döşemeli baza.',
    description: 'A soft-form upholstered base with a distinctively rounded corner profile — designed for interiors where hard edges are unwanted. Solid hardwood frame, full-perimeter upholstery, and 40+ fabric options.',
    description_tr: 'Sert kenarların istenilmediği mekânlar için tasarlanmış belirgin yuvarlatılmış köşe profilli yumuşak formlu döşemeli baza. Sağlam sert ahşap çerçeve, tam çevre döşeme ve 40+ kumaş seçeneği.',
    features: ['Rounded corner profile', 'Soft-form construction', 'Solid hardwood frame', 'Full-perimeter upholstery', '40+ fabric selection'],
    features_tr: ['Yuvarlatılmış köşe profili', 'Yumuşak form yapısı', 'Sağlam sert ahşap çerçeve', 'Tam çevre döşeme', '40+ kumaş seçimi'],
    specs: { 'Profile': 'Rounded corners', 'Frame': 'Solid hardwood', 'Upholstery': 'Full perimeter', 'Weight Capacity': '300 kg', 'Sizes Available': 'Single to Super King + Custom' },
    specs_tr: { 'Profil': 'Yuvarlatılmış köşeler', 'Çerçeve': 'Sağlam sert ahşap', 'Döşeme': 'Tam çevre', 'Ağırlık Kapasitesi': '300 kg', 'Mevcut Boyutlar': 'Tek kişilikten Süper King\'e + Özel' },
    customOptions: ['Fabric selection (40+ options)', 'Leg height adjustment', 'Custom dimensions'],
    fabrics: ['alabaster', 'linen', 'cream', 'oyster', 'stone', 'charcoal'],
    imageFile: 'rounded_base_1.jpg',
    featured: false,
  },
];

const categoryPlaceholders = {
  'bed-base': {
    image: 'brand_assets/placeholders/bed-base-main.svg',
    thumb: 'brand_assets/placeholders/bed-base-thumb.svg',
  },
  mattress: {
    image: 'brand_assets/placeholders/mattress-main.svg',
    thumb: 'brand_assets/placeholders/mattress-thumb.svg',
  },
  topper: {
    image: 'brand_assets/placeholders/topper-main.svg',
    thumb: 'brand_assets/placeholders/topper-thumb.svg',
  },
  headboard: {
    image: 'https://placehold.co/1200x900/ede8e0/03163D?text=Headboard',
    thumb: 'https://placehold.co/600x450/ede8e0/03163D?text=Headboard',
  },
};

function applyProductImages(seedProducts) {
  return seedProducts.map(product => {
    const fallback = categoryPlaceholders[product.category] || {};
    const folder   = `images/products/${product.category}/`;
    const rawFile  = product.imageFile || `${product.id}-main.jpg`;
    // Normalize old naming: '1_aura_xxl.jpg' → 'aura_xxl_1.jpg'
    const file     = rawFile.replace(/^(\d+)_(.+?)(\.[^.]+)$/, '$2_1$3');
    const imgSrc   = `${folder}${file}`;
    const ext      = file.match(/\.[^.]+$/)?.[0] || '.jpg';
    // Strip trailing _N to get clean slug for gallery probing
    const baseName = file.replace(/\.[^.]+$/, '');
    const baseSlug = baseName.replace(/_\d+$/, '');
    return {
      ...product,
      image:         imgSrc,
      thumb:         imgSrc,
      imageFolder:   folder,
      imageBaseName: baseName,
      imageBaseSlug: baseSlug,
      imageExt:      ext,
      imageFallback: fallback.image || '',
    };
  });
}

const products = applyProductImages(baseProducts);

// ═══════════════════════════════════════════════════════
// FABRIC PALETTE
// ═══════════════════════════════════════════════════════

const fabrics = {
  alabaster:    { name: 'Alabaster',       hex: '#F2EDE4', group: 'neutral' },
  linen:        { name: 'Natural Linen',   hex: '#D8CAB0', group: 'neutral' },
  oyster:       { name: 'Oyster',          hex: '#E8DFD0', group: 'neutral' },
  cream:        { name: 'Warm Cream',      hex: '#F0E8D8', group: 'neutral' },
  ecru:         { name: 'Écru',            hex: '#EDE4D3', group: 'neutral' },
  biscuit:      { name: 'Biscuit',         hex: '#D4B896', group: 'neutral' },
  ivory:        { name: 'Ivory',           hex: '#FAFAF5', group: 'neutral' },
  sand:         { name: 'Desert Sand',     hex: '#C8A87A', group: 'warm'    },
  camel:        { name: 'Camel',           hex: '#B8934A', group: 'warm'    },
  cognac:       { name: 'Cognac',          hex: '#9B5E3A', group: 'warm'    },
  clay:         { name: 'Clay',            hex: '#A87060', group: 'warm'    },
  taupe:        { name: 'Taupe',           hex: '#9E907C', group: 'neutral' },
  stone:        { name: 'Stone',           hex: '#B8B0A8', group: 'cool'    },
  mist:         { name: 'Dove Mist',       hex: '#C8CDD4', group: 'cool'    },
  sage:         { name: 'Sage Green',      hex: '#8A9E8B', group: 'cool'    },
  slate:        { name: 'Slate Blue',      hex: '#7B8FA1', group: 'cool'    },
  ocean:        { name: 'Ocean',           hex: '#4A6E8A', group: 'cool'    },
  forest:       { name: 'Forest',          hex: '#4A6249', group: 'cool'    },
  storm:        { name: 'Storm Grey',      hex: '#6A7280', group: 'cool'    },
  pewter:       { name: 'Pewter',          hex: '#8A8E94', group: 'cool'    },
  graphite:     { name: 'Graphite',        hex: '#4A4E54', group: 'dark'    },
  charcoal:     { name: 'Charcoal',        hex: '#3A3D42', group: 'dark'    },
  midnight:     { name: 'Midnight Blue',   hex: '#1B2C4A', group: 'dark'    },
  'navy-fabric':{ name: 'Deep Navy',       hex: '#03163D', group: 'dark'    },
  onyx:         { name: 'Onyx',            hex: '#2C2C2C', group: 'dark'    },
  ebony:        { name: 'Ebony',           hex: '#1E1E1E', group: 'dark'    },
  anthracite:   { name: 'Anthracite',      hex: '#2D3032', group: 'dark'    },
  carbon:       { name: 'Carbon',          hex: '#383838', group: 'dark'    },
};

// ═══════════════════════════════════════════════════════
// CATEGORIES
// ═══════════════════════════════════════════════════════

const categories = [
  {
    id: 'bed-base',
    name: 'Bed Base Systems',
    name_tr: 'Baza Sistemleri',
    count: 6,
    description: 'Adjustable, platform, divan, ottoman, and upholstered bases — all available in custom sizes and fabric specifications.',
    description_tr: 'Ayarlanabilir, platform, divan, ottoman ve döşemeli bazalar — tamamı özel ölçü ve kumaş spesifikasyonlarıyla sunulur.',
    image: 'https://placehold.co/800x600/f0edec/03163D?text=Bed+Base+Systems',
  },
  {
    id: 'mattress',
    name: 'Mattresses',
    name_tr: 'Yataklar',
    count: 6,
    description: 'Pocket spring, memory foam, latex, and hybrid mattresses built to custom specifications for every comfort requirement.',
    description_tr: 'Her konfor gereksinimine göre özel spesifikasyonlarla üretilen cep yaylı, visco köpük, lateks ve hibrit yataklar.',
    image: 'https://placehold.co/800x600/e5e2e1/03163D?text=Mattresses',
  },
  {
    id: 'topper',
    name: 'Toppers',
    name_tr: 'Pedler',
    count: 3,
    description: 'Memory foam, natural latex, and wool topper systems designed to enhance mattress comfort and surface performance.',
    description_tr: 'Yatak konforunu ve yüzey performansını geliştirmek için tasarlanmış visco köpük, doğal lateks ve yün ped sistemleri.',
    image: 'https://placehold.co/800x600/dcd9d9/03163D?text=Toppers',
  },
  {
    id: 'headboard',
    name: 'Headboards',
    name_tr: 'Başlıklar',
    count: 19,
    description: 'Upholstered headboards in 19 models. Available in 40+ fabrics across all standard sizes and custom dimensions.',
    description_tr: 'Döşemeli başlıklar, 19 modelde. Tüm standart ölçülerde ve özel boyutlarda 40+ kumaşta mevcut.',
    image: 'https://placehold.co/800x600/ede8e0/03163D?text=Headboards',
  },
];

// ═══════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════

function getProductById(id) {
  return products.find(p => p.id === id) || null;
}

function getProductsByCategory(cat) {
  return products.filter(p => p.category === cat);
}

function getFeaturedProducts() {
  return products.filter(p => p.featured);
}

function getFabric(id) {
  return fabrics[id] || { name: id, hex: '#ccc', group: 'neutral' };
}

function getRelated(product, limit = 4) {
  return products
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}

if (typeof window !== 'undefined') {
  window.ElseHomeData = {
    products,
    categories,
    fabrics,
    getProductById,
    getProductsByCategory,
    getFeaturedProducts,
    getFabric,
    getRelated,
  };
}
